// HAND-WRITTEN plain-English translations — one sentence or two per compound, in everyday words,
// answering "what actually IS this?" before any science. The scientific mechanism lives in
// compound-depth-data.ts; this file is the human translation layer rendered ABOVE it.
//
// Rules (enforced by tests/unit/compound-plain-english.test.ts):
// - Every compound in COMPOUND_DEPTH has a line here, and every line here maps to a real compound.
// - No jargon: no "agonist", "receptor", "analog", "upregulation", etc. If a term needs a
//   biology degree, translate it ("mitochondria" gets "the cell's power plants").
// - Research framing only — what it is and what researchers study it for. Never efficacy,
//   dosing, or human-use advice. Honest caveats welcome.

export const PLAIN_ENGLISH: Record<string, string> = {
  "bpc-157": "A lab-made copy of a tiny piece of a protein your stomach makes to protect itself. Researchers study whether that same protect-and-repair signal helps injured tendons, muscle, and gut lining heal — gym circles nickname it the 'Wolverine peptide', but the evidence is almost entirely from animal studies.",
  "pentadeca-arginate": "The same active ingredient as BPC-157, packaged in a different salt form claimed to be more stable. It's a rebrand with no published research of its own — everything said about it leans on BPC-157's animal data.",
  "tb-500": "A lab-made piece of a repair protein found in nearly every cell of your body, which helps cells move to where damage is. The classic partner to BPC-157 in recovery research — though the injectable version itself has never been tested in people.",
  "thymosin-beta-4": "The full-size repair protein that TB-500 is cut from — it helps cells migrate into wounds to patch them. Its real human trials are eye-drop versions for cornea and dry-eye disease, not injections.",
  "ghk-cu": "A tiny copper-carrying molecule your body makes naturally, famous in skincare. It ferries copper to the enzymes that rebuild collagen and elastin, which is why it's studied for skin, hair, and wound repair.",
  "kpv": "A three-building-block fragment of one of the body's calming hormones, studied for quieting inflammation — especially in the gut.",
  "ara-290": "A small piece of EPO (the hormone that makes red blood cells) re-engineered to keep only its tissue-calming, nerve-protecting side. Studied mainly for nerve pain.",
  "larazotide": "A molecule that helps tighten the seams between the cells lining your gut. Studied in celiac disease for calming so-called leaky gut.",
  "ll-37": "Your body's own built-in antibiotic — a molecule the immune system uses to punch holes in microbes and rally immune cells. Studied for infections and wound healing.",
  "ipamorelin": "The 'polite' growth-hormone releaser: it prompts a clean pulse of your own growth hormone with little effect on stress hormones or hunger. That selectivity is why it's the usual partner to CJC-1295 in research.",
  "cjc-1295": "A lab-made, longer-lasting version of the brain signal that tells your pituitary gland to release growth hormone. Studied as a way to keep growth-hormone output raised for days at a time instead of minutes.",
  "sermorelin": "A lab-made copy of the brain's 'release growth hormone now' signal. It was once an approved drug (Geref); today it mostly appears in anti-aging clinics and research settings.",
  "tesamorelin": "A lab-made version of the 'release growth hormone' brain signal that IS an approved drug — Egrifta, used to reduce deep belly fat in people with HIV-related fat changes.",
  "hexarelin": "A growth-hormone-releasing molecule that also showed a separate heart-protecting effect in early research. It was never brought to market.",
  "ghrp-2": "A lab-made molecule that mimics ghrelin, the hunger hormone, to make the pituitary release growth hormone. Japan uses it as a diagnostic test for growth-hormone deficiency.",
  "ghrp-6": "One of the original growth-hormone-releasing molecules. It mimics ghrelin, the hunger hormone — so alongside a growth-hormone pulse it causes strong, real hunger.",
  "mk-677": "A pill — not an injection — that mimics the hunger hormone to raise growth hormone and IGF-1. Big-pharma trials found raised blood sugar and no strength benefit, so it was shelved and never approved.",
  "mgf": "A repair signal your muscles make right after hard or damaging exercise. It wakes up muscle stem cells to patch the damage, which is why it's studied for muscle repair.",
  "peg-mgf": "The muscle-repair signal MGF wearing a chemical raincoat so it lasts days instead of minutes. That turns a brief, local repair signal into a body-wide one — which is exactly what makes its effects unknown.",
  "igf-1-lr3": "A souped-up, longer-lasting lab version of IGF-1, the growth factor your body releases in response to growth hormone. Studied for muscle growth, with a real risk of low blood sugar.",
  "semaglutide": "The molecule behind Ozempic and Wegovy — a lab-made version of a gut fullness hormone that quiets appetite. The pharmacy product is FDA-approved; grey-market vials of it are not.",
  "tirzepatide": "The molecule behind Mounjaro and Zepbound. It mimics two gut fullness hormones at once, which is why its weight-loss trial numbers beat the single-hormone drugs.",
  "retatrutide": "The next-generation weight-loss candidate: it works on three metabolic hormone systems at once — one more than tirzepatide — with striking trial results but no approval yet.",
  "cagrilintide": "A lab-made version of amylin, a fullness hormone your body releases after meals. It slows the stomach and tells the brain you're satisfied — studied for weight loss, usually paired with semaglutide.",
  "survodutide": "A weight-loss molecule that pairs appetite suppression with a signal telling the liver to burn fat. In late-stage trials for obesity and fatty liver disease.",
  "mazdutide": "A weight-loss molecule that hits two hormone systems at once — a fullness signal plus one that raises energy burn. Approved in China, but not in the US.",
  "liraglutide": "The earlier, once-daily cousin of Ozempic — a lab-made version of a gut fullness hormone, approved for diabetes as Victoza and for weight loss as Saxenda.",
  "aod-9604": "A small piece of the human growth-hormone molecule, keeping the part thought to burn fat and dropping the growth effects. Its biggest human trial did not beat placebo, and development stopped.",
  "hgh-fragment-176-191": "The 'fat-burning tail' of the growth-hormone molecule — a small piece studied for whether it can trigger fat breakdown without the growth effects of the whole hormone.",
  "tesofensine": "An appetite-suppressing weight-loss pill that raises three brain chemicals at once. It worked in trials but stalled in the US over raised heart rate and blood pressure.",
  "5-amino-1mq": "A lab-made molecule that blocks an enzyme in fat tissue which acts like a brake on fat-burning. Researchers study whether releasing that brake helps the body burn more fat — so far only in mice.",
  "slu-pp-332": "An 'exercise in a pill' candidate: it switches on the cellular programs that endurance training normally activates, so treated mice burn more fat and run longer. No human has ever been dosed in a trial.",
  "epitalon": "A tiny lab-made molecule modeled on a pineal-gland extract, famous in longevity circles for cell-dish results on telomeres — the protective caps on chromosomes that shorten with age.",
  "mots-c": "A tiny protein encoded by your mitochondria — the cell's power plants. Studied as a possible 'exercise in a molecule' for blood-sugar control and metabolism.",
  "ss-31": "A molecule that docks onto the inner membrane of mitochondria — the cell's power plants — to steady energy production in stressed tissue. In late-stage trials for rare muscle and heart diseases.",
  "humanin": "A small protein made by your own mitochondria that seems to protect cells under stress. Blood levels fall with age, which is why longevity researchers track it.",
  "nad-plus": "A molecule every cell uses to turn food into energy and repair DNA. Levels fall with age, so raising them — usually via the precursors NMN or NR — is a cornerstone of longevity research.",
  "thymalin": "An extract of calf thymus — the gland that trains your immune cells — used in Russia since the 1980s to try to restore immune function after illness or radiation.",
  "pinealon": "A three-building-block 'bioregulator' molecule from Russian longevity research, studied in aged animals for memory and brain-cell protection.",
  "semax": "A focus-and-recovery molecule from Russian research — a fragment of a stress hormone repurposed to boost the brain's own growth factors. Prescribed in Russia after strokes; often paired with Selank.",
  "selank": "A calming molecule from Russian research, studied for anxiety — reported to take the edge off without sedation. Nearly all of the evidence comes from Russian trials.",
  "dihexa": "A lab-made molecule studied for its striking ability, in animal brains, to encourage neurons to form new connections. Of interest for memory and brain-aging research; almost no human data exist.",
  "cerebrolysin": "A mixture of small protein pieces made from purified pig brain, given as an injection in some countries to support recovery after strokes and in dementia. Not approved in the US.",
  "p21": "A brain-protection molecule designed to block an enzyme that goes haywire and kills neurons after strokes and in neurodegenerative disease. Animal research only.",
  "argireline": "A skin-cream ingredient that works like a milder, rub-on cousin of Botox: it tells facial muscles to relax slightly so expression lines soften.",
  "snap-8": "A skin-cream ingredient — the bigger sibling of Argireline — that nudges facial muscles to relax so expression wrinkles soften.",
  "matrixyl": "A skincare ingredient that pairs a collagen-fragment 'rebuild' signal with a fatty tail that helps it sink into skin. Studied for softening wrinkles.",
  "melanotan-1": "A lab-made version of the hormone that tells your skin to make pigment. The regulated version (Scenesse) is approved for a rare light-sensitivity disease — grey-market tanning vials are not that product.",
  "melanotan-2": "The 'tanning peptide' — it darkens skin without sun and also stirs libido and appetite circuits. Case reports tie it to new or changing moles and other serious harms, so its safety record is genuinely concerning.",
  "pt-141": "The 'desire molecule' — it works on arousal circuits in the brain rather than on blood flow. Approved as Vyleesi for low sexual desire in premenopausal women.",
  "kisspeptin-10": "A fragment of the molecule that kick-starts the body's reproductive-hormone chain. Studied in fertility clinics as a gentler trigger for ovulation in IVF.",
  "gonadorelin": "A lab-made copy of the brain signal that starts the reproductive-hormone chain. Once an approved diagnostic drug, now mostly seen in research on testosterone and fertility signaling.",
  "thymosin-alpha-1": "A thymus-gland molecule that helps coordinate the immune system's response. Approved in 35+ countries as Zadaxin for hepatitis B — but not in the US.",
  "thymulin": "A zinc-dependent molecule from the thymus that helps young immune cells mature. Studied in immune aging — and it literally stops working without zinc.",
  "dsip": "The 'deep-sleep' molecule, first found in the blood of sleeping rabbits. Studied — with mixed results — for whether it nudges the brain toward restful sleep and dampens stress hormones.",
  "adipotide": "A lab-made molecule designed to cut off the blood supply fat tissue needs, so fat cells die off. It caused weight loss in monkeys but also stressed their kidneys, which halted development.",
  "follistatin-344": "A protein that blocks myostatin — the body's natural 'stop growing muscle' signal. Studied for muscle-wasting diseases, mostly using gene therapy rather than the injectable sold online.",
  "vip": "A messenger molecule your body uses to relax airways, widen blood vessels, and calm inflammation. Studied for mold-related illness and, as a synthetic version, for severe respiratory failure.",
  "oxytocin": "The 'bonding hormone', released during touch, birth, and breastfeeding. The approved drug form (Pitocin) is used in delivery rooms; researchers study nasal versions for trust, mood, and social behavior.",
  "glutathione": "The body's own 'master antioxidant', made in every cell. Popular in wellness and skin-brightening circles — though regulators have specifically warned against injectable versions.",
};
