import type { AgentRun, Compound, Product, Vendor } from "./types";

// Seeded demo records omit `origin`; it defaults to 'demo' in the DB and mapper.
// The public Compound/Vendor/Product types require `origin` because every record
// read back from the DB always carries it.
type SeedCompound = Omit<Compound, "origin">;
type SeedVendor = Omit<Vendor, "origin">;
type SeedProduct = Omit<Product, "origin" | "externalUrl">;

export const compounds: SeedCompound[] = [
  {
    slug: "bpc-157",
    name: "BPC-157",
    shorthand: "BPC",
    category: "Synthetic peptide",
    description:
      "A synthetic pentadecapeptide frequently referenced in preclinical research literature. Listings are normalized by declared form, quantity, evidence source, and batch linkage.",
    aliases: ["Body protection compound 157", "BPC 157 acetate"],
    listings: 3,
    medianPrice: 52,
    priceChange: -4.8,
    documentationCoverage: 67,
    accent: ["#6d5dfc", "#9f8dff", "#c9fbff"],
    researchNote:
      "Research summaries on VIAL describe published literature only. They do not establish the identity, quality, safety, or legal status of any listed physical product.",
  },
  {
    slug: "kpv",
    name: "KPV",
    shorthand: "KPV",
    category: "Tripeptide",
    description:
      "A short synthetic peptide appearing in preclinical literature. The market view separates compound-level research from vendor-level product evidence.",
    aliases: ["Lys-Pro-Val", "KPV peptide"],
    listings: 2,
    medianPrice: 44,
    priceChange: 2.1,
    documentationCoverage: 50,
    accent: ["#3859ff", "#67a8ff", "#a6f4ff"],
    researchNote:
      "The compound page is informational. Vendor documents and physical product testing are displayed as separate evidence layers.",
  },
  {
    slug: "mots-c",
    name: "MOTS-c",
    shorthand: "MOTS",
    category: "Mitochondrial-derived peptide",
    description:
      "A mitochondrial-derived peptide discussed in experimental research. Listings are grouped by declared quantity and documentation freshness.",
    aliases: ["MOTS c", "Mitochondrial open reading frame peptide"],
    listings: 2,
    medianPrice: 68,
    priceChange: -1.2,
    documentationCoverage: 100,
    accent: ["#855cff", "#d66dff", "#ffd6f7"],
    researchNote:
      "A publication about a molecule is not evidence that a commercial vial contains that molecule. VIAL keeps those concepts separate.",
  },
  {
    slug: "ghk-cu",
    name: "GHK-Cu",
    shorthand: "GHK",
    category: "Copper peptide",
    description:
      "A copper-binding tripeptide used across scientific and cosmetic research contexts. Product profiles distinguish declared compound form from report scope.",
    aliases: ["Copper tripeptide-1", "GHK copper"],
    listings: 2,
    medianPrice: 59,
    priceChange: 3.4,
    documentationCoverage: 50,
    accent: ["#0f9f88", "#42d9bd", "#c6fff2"],
    researchNote:
      "Product evidence can establish only what a named method found in a named sample. It does not establish suitability for a particular use.",
  },
  {
    slug: "semax",
    name: "Semax",
    shorthand: "SMX",
    category: "Synthetic heptapeptide",
    description:
      "A synthetic peptide represented in a limited set of research and regional pharmaceutical contexts. Listings are shown without outcome claims.",
    aliases: ["MEHFPGP", "Semax peptide"],
    listings: 2,
    medianPrice: 48,
    priceChange: 0.8,
    documentationCoverage: 50,
    accent: ["#e26b32", "#ff9a66", "#ffe3cc"],
    researchNote:
      "Regulatory and research contexts vary by jurisdiction. VIAL records dated sources rather than assigning a permanent legal label.",
  },
  {
    slug: "epitalon",
    name: "Epitalon",
    shorthand: "EPT",
    category: "Synthetic tetrapeptide",
    description:
      "A synthetic tetrapeptide found in experimental literature. The prototype tracks pricing, documentation, and seller history without medical guidance.",
    aliases: ["Epithalon", "Ala-Glu-Asp-Gly"],
    listings: 1,
    medianPrice: 72,
    priceChange: -2.6,
    documentationCoverage: 100,
    accent: ["#22272f", "#687384", "#d8dee7"],
    researchNote:
      "Evidence cards describe source quality and omissions. Unknown fields remain visible rather than being converted into an overall safety score.",
  },
];

export const vendors: SeedVendor[] = [
  {
    slug: "northstar-research",
    name: "Northstar Research",
    initials: "NR",
    description:
      "A fictional research supplier used to demonstrate claimed-profile, catalog, pricing, and evidence-history interfaces.",
    location: "Austin, TX",
    founded: "2023",
    profileStatus: "participating",
    productCount: 4,
    documentationCurrent: 88,
    medianShipDays: 3,
    supportScore: 4.8,
    lastObserved: "18 minutes ago",
    accent: ["#6d5dfc", "#b9afff"],
    history: [
      { date: "Jul 18, 2026", event: "BPC-157 listing price updated", type: "catalog" },
      { date: "Jul 16, 2026", event: "Current batch report confirmed by issuer", type: "document" },
      { date: "Jul 02, 2026", event: "Seller profile verification renewed", type: "profile" },
      { date: "Jun 28, 2026", event: "Refund policy snapshot updated", type: "policy" },
    ],
  },
  {
    slug: "helix-science",
    name: "Helix Science",
    initials: "HS",
    description:
      "A demo catalog with a strong public-document trail and mixed batch linkage, shown to illustrate the interface.",
    location: "Raleigh, NC",
    founded: "2022",
    profileStatus: "claimed",
    productCount: 3,
    documentationCurrent: 76,
    medianShipDays: 4,
    supportScore: 4.5,
    lastObserved: "42 minutes ago",
    accent: ["#3859ff", "#8cc5ff"],
    history: [
      { date: "Jul 17, 2026", event: "GHK-Cu document added", type: "document" },
      { date: "Jul 11, 2026", event: "Shipping estimate changed to 3–5 days", type: "catalog" },
      { date: "Jun 19, 2026", event: "Profile claimed by vendor representative", type: "profile" },
    ],
  },
  {
    slug: "meridian-biosciences",
    name: "Meridian Biosciences",
    initials: "MB",
    description:
      "A fictional independent profile showing how VIAL can aggregate public catalog and document information before seller participation.",
    location: "Phoenix, AZ",
    founded: "2024",
    profileStatus: "unclaimed",
    productCount: 2,
    documentationCurrent: 62,
    medianShipDays: 5,
    supportScore: 4.2,
    lastObserved: "2 hours ago",
    accent: ["#855cff", "#e2b3ff"],
    history: [
      { date: "Jul 18, 2026", event: "MOTS-c availability changed", type: "catalog" },
      { date: "Jul 07, 2026", event: "Public report date normalized", type: "document" },
    ],
  },
  {
    slug: "arcwell-analytics",
    name: "Arcwell Analytics",
    initials: "AA",
    description:
      "A fictional vendor profile used to demonstrate evidence freshness, price history, and catalog comparison.",
    location: "Denver, CO",
    founded: "2021",
    profileStatus: "claimed",
    productCount: 3,
    documentationCurrent: 71,
    medianShipDays: 3,
    supportScore: 4.6,
    lastObserved: "36 minutes ago",
    accent: ["#e26b32", "#ffbf91"],
    history: [
      { date: "Jul 15, 2026", event: "Semax report moved to stale status", type: "document" },
      { date: "Jul 10, 2026", event: "KPV price reduced", type: "catalog" },
      { date: "Jun 30, 2026", event: "Profile contact reverified", type: "profile" },
    ],
  },
  {
    slug: "lattice-research",
    name: "Lattice Research",
    initials: "LR",
    description:
      "A fictional supplier with current issuer-confirmed documentation and a compact catalog.",
    location: "Boston, MA",
    founded: "2024",
    profileStatus: "participating",
    productCount: 2,
    documentationCurrent: 94,
    medianShipDays: 2,
    supportScore: 4.9,
    lastObserved: "9 minutes ago",
    accent: ["#0f9f88", "#74ead4"],
    history: [
      { date: "Jul 18, 2026", event: "MOTS-c report confirmation refreshed", type: "document" },
      { date: "Jul 14, 2026", event: "Fulfillment feed connected", type: "profile" },
      { date: "Jul 08, 2026", event: "Catalog quantity field corrected", type: "catalog" },
    ],
  },
  {
    slug: "signal-science",
    name: "Signal Science",
    initials: "SS",
    description:
      "A fictional profile illustrating vendor-published evidence that has not been independently confirmed.",
    location: "Portland, OR",
    founded: "2022",
    profileStatus: "unclaimed",
    productCount: 1,
    documentationCurrent: 52,
    medianShipDays: 5,
    supportScore: 4.1,
    lastObserved: "5 hours ago",
    accent: ["#22272f", "#9ba5b4"],
    history: [
      { date: "Jul 13, 2026", event: "GHK-Cu public report discovered", type: "document" },
      { date: "Jun 26, 2026", event: "Domain terms snapshot updated", type: "policy" },
    ],
  },
];

export const products: SeedProduct[] = [
  {
    slug: "northstar-bpc-157-10mg",
    name: "BPC-157",
    compoundSlug: "bpc-157",
    vendorSlug: "northstar-research",
    quantity: "10 mg",
    form: "Lyophilized research material",
    price: 54,
    previousPrice: 58,
    currency: "USD",
    availability: "In stock",
    shipping: "2–4 business days",
    evidenceLevel: "issuer-confirmed",
    evidenceLabel: "Issuer confirmed",
    reportDate: "Jul 16, 2026",
    reportIssuer: "Aperture Analytical (fictional)",
    reportConfirmed: true,
    batchCode: "NS-BPC-0716",
    batchLinked: true,
    sampleOrigin: "Vendor-selected sample",
    lastChecked: "18 minutes ago",
    rating: 4.8,
    reviewCount: 184,
    featured: true,
    checkoutMode: "marketplace-pending",
    priceHistory: [61, 59, 60, 58, 58, 57, 54, 54],
    accent: ["#6d5dfc", "#9f8dff", "#d9d3ff"],
    evidence: [
      { label: "Document authenticity", status: "established", detail: "Report identifier confirmed by the named issuer." },
      { label: "Batch linkage", status: "established", detail: "The public report names the same declared batch code as the listing." },
      { label: "Chemical identity", status: "established", detail: "Identity was reported by LC-MS in the uploaded document." },
      { label: "Declared quantity", status: "partial", detail: "Quantity is reported, but VIAL did not select the sample." },
      { label: "Sterility", status: "not-tested", detail: "No sterility result appears in the current evidence package." },
      { label: "Endotoxin", status: "not-tested", detail: "No endotoxin result appears in the current evidence package." },
    ],
  },
  {
    slug: "helix-bpc-157-10mg",
    name: "BPC-157",
    compoundSlug: "bpc-157",
    vendorSlug: "helix-science",
    quantity: "10 mg",
    form: "Lyophilized research material",
    price: 49,
    previousPrice: 49,
    currency: "USD",
    availability: "Low stock",
    shipping: "3–5 business days",
    evidenceLevel: "vendor-published",
    evidenceLabel: "Vendor-published report",
    reportDate: "Jun 28, 2026",
    reportIssuer: "Nova Assay Group (fictional)",
    reportConfirmed: false,
    batchCode: "HX-2406-BPC",
    batchLinked: true,
    sampleOrigin: "Vendor-selected sample",
    lastChecked: "42 minutes ago",
    rating: 4.5,
    reviewCount: 96,
    checkoutMode: "information-only",
    priceHistory: [47, 47, 48, 49, 49, 49, 49, 49],
    accent: ["#3859ff", "#67a8ff", "#d9efff"],
    evidence: [
      { label: "Document authenticity", status: "partial", detail: "The document is public, but the issuer has not confirmed the report identifier." },
      { label: "Batch linkage", status: "established", detail: "The batch code matches the seller listing." },
      { label: "Chemical identity", status: "partial", detail: "Identity is reported in a vendor-provided file." },
      { label: "Declared quantity", status: "unknown", detail: "No quantitative fill assay was located." },
      { label: "Sterility", status: "not-tested", detail: "No sterility result was located." },
      { label: "Endotoxin", status: "not-tested", detail: "No endotoxin result was located." },
    ],
  },
  {
    slug: "meridian-bpc-157-5mg",
    name: "BPC-157",
    compoundSlug: "bpc-157",
    vendorSlug: "meridian-biosciences",
    quantity: "5 mg",
    form: "Lyophilized research material",
    price: 41,
    currency: "USD",
    availability: "In stock",
    shipping: "4–6 business days",
    evidenceLevel: "public-only",
    evidenceLabel: "Public catalog only",
    reportDate: "Not located",
    reportIssuer: "Unknown",
    reportConfirmed: false,
    batchCode: "Not disclosed",
    batchLinked: false,
    sampleOrigin: "No sample evidence located",
    lastChecked: "2 hours ago",
    rating: 4.2,
    reviewCount: 41,
    checkoutMode: "information-only",
    priceHistory: [43, 43, 42, 42, 41, 41, 41, 41],
    accent: ["#855cff", "#c582ff", "#f0ddff"],
    evidence: [
      { label: "Document authenticity", status: "unknown", detail: "No current report was located." },
      { label: "Batch linkage", status: "unknown", detail: "No batch identifier is visible on the public listing." },
      { label: "Chemical identity", status: "unknown", detail: "No physical-product identity evidence was located." },
      { label: "Declared quantity", status: "unknown", detail: "No quantitative evidence was located." },
      { label: "Sterility", status: "unknown", detail: "Not established." },
      { label: "Endotoxin", status: "unknown", detail: "Not established." },
    ],
  },
  {
    slug: "arcwell-kpv-10mg",
    name: "KPV",
    compoundSlug: "kpv",
    vendorSlug: "arcwell-analytics",
    quantity: "10 mg",
    form: "Lyophilized research material",
    price: 43,
    previousPrice: 47,
    currency: "USD",
    availability: "In stock",
    shipping: "2–4 business days",
    evidenceLevel: "issuer-confirmed",
    evidenceLabel: "Issuer confirmed",
    reportDate: "Jul 10, 2026",
    reportIssuer: "Aperture Analytical (fictional)",
    reportConfirmed: true,
    batchCode: "AA-KPV-0710",
    batchLinked: true,
    sampleOrigin: "Vendor-selected sample",
    lastChecked: "36 minutes ago",
    rating: 4.6,
    reviewCount: 78,
    featured: true,
    checkoutMode: "marketplace-pending",
    priceHistory: [49, 48, 48, 47, 46, 45, 43, 43],
    accent: ["#e26b32", "#ff9a66", "#ffe3cc"],
    evidence: [
      { label: "Document authenticity", status: "established", detail: "The named issuer confirmed the report identifier." },
      { label: "Batch linkage", status: "established", detail: "Report and listing share the same batch code." },
      { label: "Chemical identity", status: "established", detail: "Identity is reported by the issuing laboratory." },
      { label: "Declared quantity", status: "partial", detail: "A quantity result is reported for a vendor-selected sample." },
      { label: "Sterility", status: "not-tested", detail: "No sterility panel is included." },
      { label: "Endotoxin", status: "not-tested", detail: "No endotoxin panel is included." },
    ],
  },
  {
    slug: "northstar-kpv-5mg",
    name: "KPV",
    compoundSlug: "kpv",
    vendorSlug: "northstar-research",
    quantity: "5 mg",
    form: "Lyophilized research material",
    price: 45,
    currency: "USD",
    availability: "In stock",
    shipping: "2–4 business days",
    evidenceLevel: "vendor-published",
    evidenceLabel: "Vendor-published report",
    reportDate: "May 22, 2026",
    reportIssuer: "Nova Assay Group (fictional)",
    reportConfirmed: false,
    batchCode: "NS-KPV-0522",
    batchLinked: true,
    sampleOrigin: "Vendor-selected sample",
    lastChecked: "18 minutes ago",
    rating: 4.7,
    reviewCount: 61,
    checkoutMode: "information-only",
    priceHistory: [44, 44, 44, 45, 45, 45, 45, 45],
    accent: ["#3859ff", "#67a8ff", "#d7f0ff"],
    evidence: [
      { label: "Document authenticity", status: "partial", detail: "Public report located; issuer confirmation is pending." },
      { label: "Batch linkage", status: "established", detail: "Batch code appears on both the report and listing." },
      { label: "Chemical identity", status: "partial", detail: "Identity is stated in vendor-published evidence." },
      { label: "Declared quantity", status: "unknown", detail: "No quantitative assay is shown." },
      { label: "Sterility", status: "not-tested", detail: "No sterility result is shown." },
      { label: "Endotoxin", status: "not-tested", detail: "No endotoxin result is shown." },
    ],
  },
  {
    slug: "lattice-mots-c-10mg",
    name: "MOTS-c",
    compoundSlug: "mots-c",
    vendorSlug: "lattice-research",
    quantity: "10 mg",
    form: "Lyophilized research material",
    price: 69,
    previousPrice: 72,
    currency: "USD",
    availability: "In stock",
    shipping: "1–3 business days",
    evidenceLevel: "independent",
    evidenceLabel: "Independent sample",
    reportDate: "Jul 18, 2026",
    reportIssuer: "Vector Lab Services (fictional)",
    reportConfirmed: true,
    batchCode: "LR-MOTS-0718",
    batchLinked: true,
    sampleOrigin: "Blind retail purchase",
    lastChecked: "9 minutes ago",
    rating: 4.9,
    reviewCount: 53,
    featured: true,
    checkoutMode: "marketplace-pending",
    priceHistory: [75, 74, 73, 72, 71, 70, 69, 69],
    accent: ["#0f9f88", "#42d9bd", "#c6fff2"],
    evidence: [
      { label: "Document authenticity", status: "established", detail: "The issuing laboratory confirmed the report." },
      { label: "Batch linkage", status: "established", detail: "The independently purchased sample carried the declared batch code." },
      { label: "Chemical identity", status: "established", detail: "Identity was reported using orthogonal analytical methods." },
      { label: "Declared quantity", status: "established", detail: "A quantitative assay was reported for the independently obtained sample." },
      { label: "Sterility", status: "not-tested", detail: "Sterility was outside the commissioned panel." },
      { label: "Endotoxin", status: "partial", detail: "A screening result is present; batch-wide consistency remains unknown." },
    ],
  },
  {
    slug: "meridian-mots-c-10mg",
    name: "MOTS-c",
    compoundSlug: "mots-c",
    vendorSlug: "meridian-biosciences",
    quantity: "10 mg",
    form: "Lyophilized research material",
    price: 67,
    currency: "USD",
    availability: "Low stock",
    shipping: "4–6 business days",
    evidenceLevel: "vendor-published",
    evidenceLabel: "Vendor-published report",
    reportDate: "Jun 19, 2026",
    reportIssuer: "Nova Assay Group (fictional)",
    reportConfirmed: false,
    batchCode: "MB-MC-0619",
    batchLinked: true,
    sampleOrigin: "Vendor-selected sample",
    lastChecked: "2 hours ago",
    rating: 4.2,
    reviewCount: 37,
    checkoutMode: "information-only",
    priceHistory: [65, 65, 66, 66, 67, 67, 67, 67],
    accent: ["#855cff", "#d66dff", "#ffd6f7"],
    evidence: [
      { label: "Document authenticity", status: "partial", detail: "Public report located; issuer confirmation has not been completed." },
      { label: "Batch linkage", status: "established", detail: "The report includes the displayed batch identifier." },
      { label: "Chemical identity", status: "partial", detail: "Identity is reported in vendor-controlled evidence." },
      { label: "Declared quantity", status: "partial", detail: "Quantity is reported, but sampling was vendor-controlled." },
      { label: "Sterility", status: "unknown", detail: "No sterility panel was located." },
      { label: "Endotoxin", status: "unknown", detail: "No endotoxin panel was located." },
    ],
  },
  {
    slug: "helix-ghk-cu-50mg",
    name: "GHK-Cu",
    compoundSlug: "ghk-cu",
    vendorSlug: "helix-science",
    quantity: "50 mg",
    form: "Research powder",
    price: 62,
    currency: "USD",
    availability: "In stock",
    shipping: "3–5 business days",
    evidenceLevel: "issuer-confirmed",
    evidenceLabel: "Issuer confirmed",
    reportDate: "Jul 17, 2026",
    reportIssuer: "Vector Lab Services (fictional)",
    reportConfirmed: true,
    batchCode: "HX-GHK-0717",
    batchLinked: true,
    sampleOrigin: "Vendor-selected sample",
    lastChecked: "42 minutes ago",
    rating: 4.6,
    reviewCount: 129,
    checkoutMode: "marketplace-pending",
    priceHistory: [58, 58, 59, 60, 60, 61, 62, 62],
    accent: ["#0f9f88", "#42d9bd", "#c6fff2"],
    evidence: [
      { label: "Document authenticity", status: "established", detail: "The issuing laboratory confirmed the report identifier." },
      { label: "Batch linkage", status: "established", detail: "The report names the listing batch." },
      { label: "Chemical identity", status: "established", detail: "The evidence package includes reported identity testing." },
      { label: "Declared quantity", status: "partial", detail: "A vendor-selected sample was assessed." },
      { label: "Sterility", status: "not-tested", detail: "The listed form was not represented as a sterile product." },
      { label: "Endotoxin", status: "not-tested", detail: "No endotoxin evidence is shown." },
    ],
  },
  {
    slug: "signal-ghk-cu-50mg",
    name: "GHK-Cu",
    compoundSlug: "ghk-cu",
    vendorSlug: "signal-science",
    quantity: "50 mg",
    form: "Research powder",
    price: 56,
    currency: "USD",
    availability: "In stock",
    shipping: "4–7 business days",
    evidenceLevel: "public-only",
    evidenceLabel: "Public catalog only",
    reportDate: "Not located",
    reportIssuer: "Unknown",
    reportConfirmed: false,
    batchCode: "Not disclosed",
    batchLinked: false,
    sampleOrigin: "No sample evidence located",
    lastChecked: "5 hours ago",
    rating: 4.1,
    reviewCount: 22,
    checkoutMode: "information-only",
    priceHistory: [54, 54, 55, 55, 55, 56, 56, 56],
    accent: ["#22272f", "#687384", "#d8dee7"],
    evidence: [
      { label: "Document authenticity", status: "unknown", detail: "No current report was located." },
      { label: "Batch linkage", status: "unknown", detail: "No visible batch identifier was located." },
      { label: "Chemical identity", status: "unknown", detail: "No physical-product identity evidence was located." },
      { label: "Declared quantity", status: "unknown", detail: "No quantitative evidence was located." },
      { label: "Sterility", status: "unknown", detail: "Not established." },
      { label: "Endotoxin", status: "unknown", detail: "Not established." },
    ],
  },
  {
    slug: "arcwell-semax-10mg",
    name: "Semax",
    compoundSlug: "semax",
    vendorSlug: "arcwell-analytics",
    quantity: "10 mg",
    form: "Lyophilized research material",
    price: 48,
    currency: "USD",
    availability: "In stock",
    shipping: "2–4 business days",
    evidenceLevel: "stale",
    evidenceLabel: "Evidence is stale",
    reportDate: "Jan 04, 2026",
    reportIssuer: "Aperture Analytical (fictional)",
    reportConfirmed: true,
    batchCode: "AA-SMX-0104",
    batchLinked: false,
    sampleOrigin: "Prior vendor-selected batch",
    lastChecked: "36 minutes ago",
    rating: 4.4,
    reviewCount: 67,
    checkoutMode: "information-only",
    priceHistory: [47, 47, 48, 48, 48, 48, 48, 48],
    accent: ["#e26b32", "#ff9a66", "#ffe3cc"],
    evidence: [
      { label: "Document authenticity", status: "established", detail: "The historical report was confirmed by the issuer." },
      { label: "Batch linkage", status: "unknown", detail: "The report applies to an older batch, not current inventory." },
      { label: "Chemical identity", status: "partial", detail: "Identity was reported for a prior vendor-selected sample." },
      { label: "Declared quantity", status: "unknown", detail: "Current inventory quantity has not been established." },
      { label: "Sterility", status: "unknown", detail: "Current inventory is not covered." },
      { label: "Endotoxin", status: "unknown", detail: "Current inventory is not covered." },
    ],
  },
  {
    slug: "northstar-semax-5mg",
    name: "Semax",
    compoundSlug: "semax",
    vendorSlug: "northstar-research",
    quantity: "5 mg",
    form: "Lyophilized research material",
    price: 46,
    currency: "USD",
    availability: "In stock",
    shipping: "2–4 business days",
    evidenceLevel: "vendor-published",
    evidenceLabel: "Vendor-published report",
    reportDate: "Jun 30, 2026",
    reportIssuer: "Nova Assay Group (fictional)",
    reportConfirmed: false,
    batchCode: "NS-SMX-0630",
    batchLinked: true,
    sampleOrigin: "Vendor-selected sample",
    lastChecked: "18 minutes ago",
    rating: 4.7,
    reviewCount: 49,
    checkoutMode: "information-only",
    priceHistory: [45, 45, 46, 46, 46, 46, 46, 46],
    accent: ["#6d5dfc", "#9f8dff", "#d9d3ff"],
    evidence: [
      { label: "Document authenticity", status: "partial", detail: "Public report located; issuer confirmation is pending." },
      { label: "Batch linkage", status: "established", detail: "The report and listing share a batch identifier." },
      { label: "Chemical identity", status: "partial", detail: "Identity is reported by vendor-controlled evidence." },
      { label: "Declared quantity", status: "unknown", detail: "A quantitative fill assay was not located." },
      { label: "Sterility", status: "unknown", detail: "No sterility result was located." },
      { label: "Endotoxin", status: "unknown", detail: "No endotoxin result was located." },
    ],
  },
  {
    slug: "lattice-epitalon-10mg",
    name: "Epitalon",
    compoundSlug: "epitalon",
    vendorSlug: "lattice-research",
    quantity: "10 mg",
    form: "Lyophilized research material",
    price: 72,
    previousPrice: 74,
    currency: "USD",
    availability: "In stock",
    shipping: "1–3 business days",
    evidenceLevel: "independent",
    evidenceLabel: "Independent sample",
    reportDate: "Jul 12, 2026",
    reportIssuer: "Vector Lab Services (fictional)",
    reportConfirmed: true,
    batchCode: "LR-EPT-0712",
    batchLinked: true,
    sampleOrigin: "Blind retail purchase",
    lastChecked: "9 minutes ago",
    rating: 4.9,
    reviewCount: 44,
    featured: true,
    checkoutMode: "marketplace-pending",
    priceHistory: [78, 77, 76, 75, 74, 74, 72, 72],
    accent: ["#22272f", "#687384", "#d8dee7"],
    evidence: [
      { label: "Document authenticity", status: "established", detail: "The laboratory confirmed the report identifier." },
      { label: "Batch linkage", status: "established", detail: "The sample was obtained independently and carried the declared batch code." },
      { label: "Chemical identity", status: "established", detail: "Identity was reported by the independent laboratory." },
      { label: "Declared quantity", status: "established", detail: "A quantitative assay was included in the independent panel." },
      { label: "Sterility", status: "not-tested", detail: "Sterility was not part of the commissioned panel." },
      { label: "Endotoxin", status: "not-tested", detail: "Endotoxin was not part of the commissioned panel." },
    ],
  },
];

export const agentRuns: AgentRun[] = [
  {
    id: "run_0198",
    workflow: "Vendor catalog refresh",
    target: "Northstar Research",
    status: "published",
    startedAt: "14:03:18",
    duration: "19.2s",
    tools: ["snapshot", "extract", "resolve", "diff", "audit"],
    proposedChanges: 7,
    publishedChanges: 5,
  },
  {
    id: "run_0197",
    workflow: "Document verification",
    target: "LR-MOTS-0718",
    status: "published",
    startedAt: "13:58:44",
    duration: "42.8s",
    tools: ["pdf-parse", "issuer-check", "hash", "schema-validate", "audit"],
    proposedChanges: 11,
    publishedChanges: 11,
  },
  {
    id: "run_0196",
    workflow: "Entity resolution",
    target: "Semax / MEHFPGP",
    status: "review",
    startedAt: "13:47:02",
    duration: "31.4s",
    tools: ["alias-map", "source-compare", "confidence-gate"],
    proposedChanges: 3,
    publishedChanges: 0,
    reason: "One alias match is below the 0.92 automatic publication threshold.",
  },
  {
    id: "run_0195",
    workflow: "Regulatory monitor",
    target: "Compound status graph",
    status: "blocked",
    startedAt: "13:32:09",
    duration: "17.7s",
    tools: ["official-source", "entity-map", "policy-gate"],
    proposedChanges: 4,
    publishedChanges: 0,
    reason: "Legal-status changes always require human review.",
  },
  {
    id: "run_0194",
    workflow: "Price refresh",
    target: "12 active listings",
    status: "running",
    startedAt: "14:07:41",
    duration: "Live",
    tools: ["snapshot", "extract", "currency-normalize"],
    proposedChanges: 2,
    publishedChanges: 0,
  },
];

export const getCompound = (slug: string) => compounds.find((compound) => compound.slug === slug);
export const getVendor = (slug: string) => vendors.find((vendor) => vendor.slug === slug);
export const getProduct = (slug: string) => products.find((product) => product.slug === slug);
export const getProductsByCompound = (slug: string) => products.filter((product) => product.compoundSlug === slug);
export const getProductsByVendor = (slug: string) => products.filter((product) => product.vendorSlug === slug);
export const getFeaturedProducts = () => products.filter((product) => product.featured);
