"use client";

import { Copy, Loader2, RadioTower } from "lucide-react";
import { useState } from "react";
import { primaryButton, secondaryButton, StatusPill } from "./seller-ui";

type Endpoint = { id: string; url: string; status: string; events: string[] | string; secret_prefix: string; last_delivery_at?: string | null };
type Delivery = { id: string; endpoint_id: string; event_type: string; status: string; response_status?: number | null; created_at: string };
function list(value: string[] | string) { if (Array.isArray(value)) return value; try { const parsed=JSON.parse(value) as unknown; return Array.isArray(parsed)?parsed.map(String):[]; } catch { return []; } }

export function DeveloperWebhookClient({ initialEndpoints, initialDeliveries }: { initialEndpoints: Endpoint[]; initialDeliveries: Delivery[] }) {
  const [endpoints,setEndpoints]=useState(initialEndpoints); const [deliveries,setDeliveries]=useState(initialDeliveries); const [secret,setSecret]=useState<string|null>(null); const [loading,setLoading]=useState(false); const [message,setMessage]=useState<string|null>(null);
  async function refresh(){const response=await fetch("/api/v1/seller/webhooks",{cache:"no-store"});if(response.ok){const body=await response.json();setEndpoints(body.endpoints??[]);setDeliveries(body.deliveries??[])}}
  async function create(formData:FormData){setLoading(true);setMessage(null);setSecret(null);const events=formData.getAll("events").map(String);const response=await fetch("/api/v1/seller/webhooks",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({url:String(formData.get("url")??""),events})});const body=await response.json();if(response.ok){setSecret(body.secret);setMessage("Endpoint created");await refresh()}else setMessage(body.error??"Endpoint creation failed");setLoading(false)}
  async function test(endpointId:string){setLoading(true);const response=await fetch("/api/v1/seller/webhooks",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"test",endpointId})});setMessage(response.ok?"Sandbox test delivery recorded":"Test failed");await refresh();setLoading(false)}
  return <div className="space-y-6"><form action={create} className="rounded-[24px] border border-black/[.07] bg-[#fafaf7] p-5"><label className="text-sm font-medium">HTTPS endpoint<input className="field mt-2" name="url" type="url" placeholder="https://seller.example.test/webhooks/vial" required /></label><fieldset className="mt-4"><legend className="text-sm font-medium">Events</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{["catalog.updated","inventory.updated","evidence.updated","order.created","order.updated"].map(event=><label key={event} className="flex items-center gap-2 rounded-xl border bg-white p-3 text-xs"><input type="checkbox" name="events" value={event} defaultChecked={event==="inventory.updated"||event==="order.created"}/>{event}</label>)}</div></fieldset><button disabled={loading} className={`${primaryButton} mt-4`}>{loading?<Loader2 className="mr-2 size-4 animate-spin"/>:<RadioTower className="mr-2 size-4"/>}Create endpoint</button>{message&&<p className="mt-3 text-xs text-black/55">{message}</p>}{secret&&<div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4"><p className="text-xs font-semibold text-amber-950">Copy the signing secret now.</p><div className="mt-2 flex gap-2"><code className="min-w-0 flex-1 overflow-x-auto rounded-xl bg-white p-2 text-xs">{secret}</code><button type="button" className={secondaryButton} onClick={()=>navigator.clipboard.writeText(secret)} aria-label="Copy webhook signing secret"><Copy className="size-4"/></button></div></div>}</form><div className="space-y-3">{endpoints.map(endpoint=><div key={endpoint.id} className="rounded-2xl border border-black/[.07] bg-white p-4"><div className="flex flex-wrap items-start gap-3"><div className="min-w-0 flex-1"><p className="truncate font-medium">{endpoint.url}</p><p className="mt-1 font-mono text-xs text-black/40">{endpoint.secret_prefix}••••</p><div className="mt-2 flex flex-wrap gap-1">{list(endpoint.events).map(event=><span key={event} className="rounded-full bg-black/[.045] px-2 py-1 text-[10px]">{event}</span>)}</div></div><StatusPill status={endpoint.status}/></div><button disabled={loading} type="button" onClick={()=>test(endpoint.id)} className={`${secondaryButton} mt-4`}>Record sandbox test</button></div>)}</div>{deliveries.length>0&&<div><p className="text-xs font-bold uppercase tracking-[.15em] text-black/35">Recent deliveries</p><div className="mt-3 space-y-2">{deliveries.slice(0,5).map(delivery=><div key={delivery.id} className="flex items-center gap-3 rounded-xl bg-black/[.035] px-3 py-2 text-xs"><span className="flex-1">{delivery.event_type}</span><StatusPill status={delivery.status}/><span className="text-black/35">{delivery.response_status??"—"}</span></div>)}</div></div>}</div>
}
