import type { QueryResultRow } from "pg";
import { getDatabase, type SqlConnection } from "@/server/db/client";
import { newId } from "@/server/db/ids";
import { combinedSimilarity, normalizeTerm } from "@/server/market-data/normalize";

export interface SearchResult {
  entityType:string;entityId:string;title:string;subtitle:string;href:string;score:number;reasons:string[];facets:Record<string,unknown>;
}
interface SearchDocumentRow extends QueryResultRow{id:string;entity_type:string;entity_id:string;title:string;subtitle:string;body:string;aliases:unknown;facets:unknown;normalized_text:string;popularity_score:number;quality_score:number}
function json<T>(value:unknown,fallback:T):T{if(typeof value==='string')try{return JSON.parse(value) as T}catch{return fallback};return (value as T)??fallback}
function href(type:string,id:string,facets:Record<string,unknown>){const slug=String(facets.slug??id.replace(/^[^:]+:/,''));if(type==='compound')return `/compounds/${slug}`;if(type==='organization')return `/vendors/${slug}`;if(type==='listing'||type==='product')return `/products/${String(facets.listingSlug??slug)}`;if(type==='source')return '/methodology';return '/search';}

export async function rebuildSearchIndex(connection?:SqlConnection){const db=connection??await getDatabase();let count=0;
 const compounds=await db.query<QueryResultRow & {id:string;slug:string;canonical_name:string;shorthand:string;category:string;description:string;aliases:unknown;documentation_coverage:number;listing_count:number}>(`SELECT * FROM compounds`);
 for(const row of compounds.rows){await upsert(db,{type:'compound',id:row.id,title:row.canonical_name,subtitle:row.category,body:row.description,aliases:[row.shorthand,...json<string[]>(row.aliases,[])],facets:{slug:row.slug,category:row.category,documentationCoverage:Number(row.documentation_coverage),listingCount:Number(row.listing_count)},popularity:Number(row.listing_count)*10,quality:Number(row.documentation_coverage)});count++;}
 const vendors=await db.query<QueryResultRow & {id:string;slug:string;display_name:string;description:string;aliases:unknown;location:string|null;profile_status:string;documentation_current:number;product_count:number}>(`SELECT * FROM organizations WHERE organization_type='vendor'`);
 for(const row of vendors.rows){await upsert(db,{type:'organization',id:row.id,title:row.display_name,subtitle:[row.location,row.profile_status].filter(Boolean).join(' · '),body:row.description,aliases:json<string[]>(row.aliases,[]),facets:{slug:row.slug,profileStatus:row.profile_status,documentationCurrent:Number(row.documentation_current),productCount:Number(row.product_count)},popularity:Number(row.product_count)*8,quality:Number(row.documentation_current)});count++;}
 const listings=await db.query<QueryResultRow & {id:string;slug:string;name:string;declared_quantity:string;declared_form:string;price:number;availability:string;evidence_label:string;evidence_level:string;vendor_name:string;vendor_slug:string;compound_name:string;compound_slug:string;rating:number;review_count:number}>(`SELECT l.id,l.slug,p.name,p.declared_quantity,p.declared_form,l.price,l.availability,l.evidence_label,l.evidence_level,o.display_name vendor_name,o.slug vendor_slug,c.canonical_name compound_name,c.slug compound_slug,l.rating,l.review_count FROM listings l JOIN products p ON p.id=l.product_id JOIN organizations o ON o.id=p.vendor_id JOIN compounds c ON c.id=p.compound_id`);
 for(const row of listings.rows){await upsert(db,{type:'listing',id:row.id,title:`${row.name} ${row.declared_quantity}`,subtitle:`${row.vendor_name} · $${Number(row.price).toFixed(2)} · ${row.availability}`,body:`${row.declared_form} ${row.evidence_label} ${row.compound_name} ${row.vendor_name}`,aliases:[row.compound_name,row.vendor_name,row.compound_slug,row.vendor_slug],facets:{slug:row.slug,listingSlug:row.slug,vendorSlug:row.vendor_slug,compoundSlug:row.compound_slug,availability:row.availability,evidenceLevel:row.evidence_level,price:Number(row.price)},popularity:Number(row.review_count)+Number(row.rating)*10,quality:row.evidence_level==='independent'?100:row.evidence_level==='issuer-confirmed'?90:row.evidence_level==='vendor-published'?65:40});count++;}
 return {count};}
async function upsert(db:SqlConnection,input:{type:string;id:string;title:string;subtitle:string;body:string;aliases:string[];facets:Record<string,unknown>;popularity:number;quality:number}){const normalized=normalizeTerm([input.title,input.subtitle,input.body,...input.aliases].join(' '));await db.query(`INSERT INTO search_documents(id,entity_type,entity_id,title,subtitle,body,aliases,facets,normalized_text,popularity_score,quality_score,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8::jsonb,$9,$10,$11,NOW()) ON CONFLICT(entity_type,entity_id) DO UPDATE SET title=EXCLUDED.title,subtitle=EXCLUDED.subtitle,body=EXCLUDED.body,aliases=EXCLUDED.aliases,facets=EXCLUDED.facets,normalized_text=EXCLUDED.normalized_text,popularity_score=EXCLUDED.popularity_score,quality_score=EXCLUDED.quality_score,updated_at=NOW()`,[`search:${input.type}:${input.id}`,input.type,input.id,input.title,input.subtitle,input.body,JSON.stringify(input.aliases),JSON.stringify(input.facets),normalized,input.popularity,input.quality]);}

export async function seedSearchSynonyms(connection?:SqlConnection){const db=connection??await getDatabase();const synonyms=[
 ['bpc-157','bpc 157','compound',1],['bpc-157','bpc157','compound',1],['bpc-157','body protection compound 157','compound',0.95],['mots-c','mots c','compound',1],['ghk-cu','ghk copper','compound',0.95],['ghk-cu','copper tripeptide 1','compound',0.9],['epitalon','epithalon','compound',0.95],['vendor','supplier','organization',0.8],['coa','certificate of analysis',null,1],['lab','laboratory',null,0.9],['in stock','available','listing',0.85],
 ];for(const [canonical,synonym,type,weight] of synonyms){await db.query(`INSERT INTO search_synonyms(id,canonical_term,synonym,normalized_synonym,entity_type,weight) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(id) DO UPDATE SET canonical_term=EXCLUDED.canonical_term,synonym=EXCLUDED.synonym,normalized_synonym=EXCLUDED.normalized_synonym,entity_type=EXCLUDED.entity_type,weight=EXCLUDED.weight`,[`syn:${String(type??'all')}:${normalizeTerm(String(synonym)).replace(/ /g,'-')}`,canonical,synonym,normalizeTerm(String(synonym)),type,weight]);}}

async function expandedQuery(query:string, connection?:SqlConnection){const db=connection??await getDatabase();const normalized=normalizeTerm(query);const result=await db.query<QueryResultRow & {canonical_term:string;synonym:string;weight:number}>(`SELECT canonical_term,synonym,weight FROM search_synonyms WHERE normalized_synonym=$1 OR normalized_synonym LIKE '%' || $1 || '%' OR $1 LIKE '%' || normalized_synonym || '%' ORDER BY weight DESC LIMIT 8`,[normalized]);return {normalized,terms:[normalized,...result.rows.map(r=>normalizeTerm(r.canonical_term))].filter((v,i,a)=>v&&a.indexOf(v)===i),synonyms:result.rows};}

export async function searchMarket(input:{query:string;types?:string[];limit?:number;actorKey?:string;log?:boolean}){return searchMarketWithConnection(await getDatabase(),input);}
async function searchMarketWithConnection(db:SqlConnection,input:{query:string;types?:string[];limit?:number;actorKey?:string;log?:boolean}):Promise<{query:string;expandedTerms:string[];results:SearchResult[];latencyMs:number}> {const started=Date.now();const query=input.query.trim();if(!query)return {query,expandedTerms:[],results:[],latencyMs:0};const expansion=await expandedQuery(query,db);const rows=await db.query<SearchDocumentRow>(`SELECT * FROM search_documents WHERE ($1::text[] IS NULL OR entity_type=ANY($1::text[]))`,[input.types?.length?input.types:null]);const scored=rows.rows.map(row=>{const aliases=json<string[]>(row.aliases,[]),facets=json<Record<string,unknown>>(row.facets,{});const fields=[{value:row.title,weight:1.4,label:'title'},{value:row.subtitle,weight:0.75,label:'subtitle'},{value:row.body,weight:0.35,label:'description'},...aliases.map(value=>({value,weight:1.1,label:'alias'}))];let lexical=0;let bestField='';for(const field of fields){for(const term of expansion.terms){const normalizedField=normalizeTerm(field.value);let score=combinedSimilarity(term,field.value)*field.weight;if(normalizedField===term)score+=0.75;if(normalizedField.startsWith(term))score+=0.45;if(normalizedField.includes(term))score+=0.3;for(const token of term.split(' '))if(token.length>1&&normalizedField.includes(token))score+=0.08; if(score>lexical){lexical=score;bestField=field.label;}}}const score=lexical*100+Number(row.quality_score)*0.12+Math.log1p(Number(row.popularity_score))*2;const reasons=[];if(bestField==='title')reasons.push('Title match');if(bestField==='alias')reasons.push('Alias or synonym match');if(bestField==='subtitle')reasons.push('Vendor or category match');if(expansion.synonyms.length)reasons.push('Query expanded');if(Number(row.quality_score)>=85)reasons.push('Strong documentation');return {entityType:row.entity_type,entityId:row.entity_id,title:row.title,subtitle:row.subtitle,href:href(row.entity_type,row.entity_id,facets),score,reasons,facets};}).filter(item=>item.score>=22).sort((a,b)=>b.score-a.score).slice(0,input.limit??20);const latencyMs=Date.now()-started;if(input.log!==false)await db.query(`INSERT INTO search_query_logs(id,query,normalized_query,actor_key,result_count,latency_ms,zero_result) VALUES($1,$2,$3,$4,$5,$6,$7)`,[newId('searchlog'),query,expansion.normalized,input.actorKey??'anonymous',scored.length,latencyMs,scored.length===0]);return {query,expandedTerms:expansion.terms,results:scored,latencyMs};}

export async function seedSearchEvaluations(connection?:SqlConnection){const db=connection??await getDatabase();const cases=[['bpc157',['cmp:bpc-157']],['body protection compound',['cmp:bpc-157']],['northstar',['org:northstar-research']],['mots c',['cmp:mots-c']],['copper tripeptide',['cmp:ghk-cu']],['helix bpc',['lst:helix-bpc-157-10mg']]];for(const [query,expected] of cases){const result=await searchMarketWithConnection(db,{query:String(query),limit:5,log:false});const actual=result.results.map(item=>item.entityId);const expectedIds=expected as string[];const first=actual.findIndex(id=>expectedIds.includes(id));const rr=first>=0?1/(first+1):0;const hits=actual.filter(id=>expectedIds.includes(id)).length;const recall=hits/Math.max(1,expectedIds.length);await db.query(`INSERT INTO search_evaluations(id,query,expected_results,actual_results,reciprocal_rank,recall_at_five,pass,notes) VALUES($1,$2,$3::jsonb,$4::jsonb,$5,$6,$7,$8)`,[newId('searcheval'),query,JSON.stringify(expectedIds),JSON.stringify(actual),rr,recall,rr>=0.5&&recall===1,JSON.stringify({expandedTerms:result.expandedTerms})]);}}

export async function getSearchQualityDashboard(){const db=await getDatabase();const [logs,evals,docs,synonyms]=await Promise.all([
 db.query<QueryResultRow & {queries:string|number;zero_results:string|number;avg_latency:number}>(`SELECT COUNT(*) queries,COUNT(*) FILTER(WHERE zero_result=TRUE) zero_results,COALESCE(AVG(latency_ms),0) avg_latency FROM search_query_logs`),
 db.query<QueryResultRow & {total:string|number;passed:string|number;mrr:number;recall:number}>(`SELECT COUNT(*) total,COUNT(*) FILTER(WHERE pass=TRUE) passed,COALESCE(AVG(reciprocal_rank),0) mrr,COALESCE(AVG(recall_at_five),0) recall FROM search_evaluations`),
 db.query<QueryResultRow & {entity_type:string;count:string|number}>(`SELECT entity_type,COUNT(*) count FROM search_documents GROUP BY entity_type ORDER BY count DESC`),
 db.query<QueryResultRow & {count:string|number}>(`SELECT COUNT(*) count FROM search_synonyms`),
 ]);const l=logs.rows[0],e=evals.rows[0];return {queries:Number(l?.queries??0),zeroResults:Number(l?.zero_results??0),avgLatency:Number(l?.avg_latency??0),evaluations:Number(e?.total??0),passed:Number(e?.passed??0),mrr:Number(e?.mrr??0),recallAtFive:Number(e?.recall??0),documents:docs.rows.map(r=>({type:r.entity_type,count:Number(r.count)})),synonyms:Number(synonyms.rows[0]?.count??0)};}

/**
 * Makes site search work on a database that was never fixture-seeded.
 *
 * The index and the synonym table are DERIVED from real records, but they were only ever built
 * inside `seedMarketDataEngine`, which is gated behind fixture seeding — and fixtures are off in
 * production. So production shipped with an empty index: every query on /search and /api/search
 * returned zero results while the underlying pages were live and correct.
 *
 * Safe to call on every boot: synonyms upsert, and the index is rebuilt only when empty.
 */
export async function ensureSearchIndex(connection?: SqlConnection): Promise<{ built: boolean; documents: number }> {
  const db = connection ?? await getDatabase();
  await seedSearchSynonyms(db);
  const existing = Number((await db.query<QueryResultRow & { count: string | number }>(
    `SELECT COUNT(*) count FROM search_documents`,
  )).rows[0]?.count ?? 0);
  if (existing > 0) return { built: false, documents: existing };
  const documents = await rebuildSearchIndex(db);
  return { built: true, documents: typeof documents === "number" ? documents : 0 };
}
