import { requirePermission } from "@/server/auth/session";
import { commerceDashboard } from "@/server/commerce/repository";
const money = (value: unknown) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(Number(value));
export default async function AdminFinancePage() {await requirePermission("finance:read");
  const dashboard = await commerceDashboard();
  const rows = dashboard.ledger as Array<Record<string, unknown>>;
  const totals = new Map<string, number>();
  for (const row of rows) totals.set(String(row.entry_type), (totals.get(String(row.entry_type)) || 0) + Number(row.amount));
  return <div><p className="text-xs font-extrabold uppercase tracking-[.18em] text-[#2b31d8]">Finance</p><h1 className="mt-2 text-4xl font-extrabold tracking-[-.05em]">Immutable commerce ledger</h1><p className="mt-3 max-w-2xl text-sm font-medium leading-6 text-[var(--muted)]">Every sandbox charge, seller payable, fee, tax, and shipping amount is recorded separately and tied to one causal root.</p><div className="mt-7 grid gap-4 md:grid-cols-4">{Array.from(totals.entries()).slice(0, 4).map(([type, value]) => <div key={type} className="ink rounded-[18px] bg-[#111214] p-5 text-white"><p className="text-xs font-bold capitalize text-[#8fa2ff]">{type.replaceAll("_", " ")}</p><p className="mt-2 text-2xl font-extrabold">{money(value)}</p></div>)}</div><div className="ink hard mt-8 overflow-x-auto rounded-[20px] bg-white p-6"><table className="w-full min-w-[850px] text-left text-sm"><thead className="text-xs font-extrabold uppercase tracking-[.06em] text-[var(--muted)]"><tr><th className="pb-3">Type</th><th>Amount</th><th>Direction</th><th>Order</th><th>Seller</th><th>Root event</th></tr></thead><tbody>{rows.map((row) => <tr key={String(row.id)} className="border-t border-[#111214]/10"><td className="py-4 font-bold capitalize">{String(row.entry_type).replaceAll("_", " ")}</td><td>{money(row.amount)}</td><td>{String(row.direction)}</td><td className="font-mono text-xs">{String(row.order_id ?? "—").slice(0, 18)}</td><td className="font-mono text-xs">{String(row.seller_id ?? "platform").slice(0, 18)}</td><td className="font-mono text-xs">{String(row.root_event_id).slice(0, 18)}</td></tr>)}</tbody></table>{!rows.length && <p className="py-8 text-center font-medium text-[var(--muted)]">Create a sandbox order to populate the ledger.</p>}</div></div>;
}
