import type { QueryResultRow } from "pg";
import { getDatabase } from "@/server/db/client";
import { newId } from "@/server/db/ids";
import { ensureCommerceSeed } from "@/server/commerce/repository";

declare global{var __vialInternalSeedPromise:Promise<void>|undefined}
async function count(table:string){const db=await getDatabase();const r=await db.query<QueryResultRow&{count:string}>(`SELECT COUNT(*)::text count FROM ${table}`);return Number(r.rows[0]?.count??0)}
async function seedInternalOps(){
 await ensureCommerceSeed(); if(await count("internal_users")) return; const db=await getDatabase();
 const users=[
  ["user:customer:nora","nora@example.test","Nora Chen","customer",["customer"],true],
  ["user:seller:marcus","marcus@helixtest.test","Marcus Vale","seller",["seller_owner","seller_finance"],true],
  ["user:staff:maya","maya@vialgrade.test","Maya Ortiz","staff",["reviewer","compliance_analyst"],true],
  ["user:staff:jon","jon@vialgrade.test","Jon Bell","staff",["finance_analyst","administrator"],true],
 ];
 for(const u of users) await db.query(`INSERT INTO internal_users(id,email,display_name,account_type,roles,mfa_enabled,last_login_at) VALUES($1,$2,$3,$4,$5::jsonb,$6,NOW()-INTERVAL '2 hours')`,[u[0],u[1],u[2],u[3],JSON.stringify(u[4]),u[5]]);
 for(const n of [["price_change","Price moved","A saved listing changed from $58 to $54."],["evidence_change","Evidence updated","A report date was refreshed after human review."],["shipment","Shipment update","Sandbox order VialGrade-1042 is marked shipped."]]) await db.query(`INSERT INTO internal_notifications(id,user_id,category,title,body,dedupe_key) VALUES($1,'user:customer:nora',$2,$3,$4,$5)`,[newId("note"),n[0],n[1],n[2],`nora:${n[0]}`]);
 for(const c of [["customer","Nora Chen","Damaged outer packaging","order_issue","high","open","Maya Ortiz"],["seller","Helix Research","Evidence document awaiting correction","evidence","normal","pending_seller","Maya Ortiz"],["customer","Avery Stone","Refund timing question","refund","normal","open","Jon Bell"]]) await db.query(`INSERT INTO support_cases(id,requester_type,requester_label,subject,category,priority,status,assignee,sla_due_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,NOW()+INTERVAL '8 hours')`,[newId("case"),...c]);
 const listing=(await db.query<QueryResultRow&{id:string}>(`SELECT id FROM listings ORDER BY created_at LIMIT 1`)).rows[0]?.id;
 if(listing){await db.query(`INSERT INTO marketplace_reviews(id,listing_id,author_user_id,verified_purchase,product_rating,shipping_rating,documentation_rating,body,moderation_status) VALUES($1,$2,'user:customer:nora',true,5,4,5,'Clear documentation and a smooth sandbox order experience.','pending')`,[newId("review"),listing]);await db.query(`INSERT INTO marketplace_reviews(id,listing_id,author_user_id,verified_purchase,product_rating,shipping_rating,documentation_rating,body,moderation_status) VALUES($1,$2,'user:customer:nora',false,2,3,1,'Suspicious repeated promotional language and unsupported claims.','flagged')`,[newId("review"),listing]);}
 await db.query(`INSERT INTO policy_versions(id,version,name,status,rules,impact_summary,created_by,activated_at) VALUES($1,12,'Sandbox eligibility v12','active',$2::jsonb,$3::jsonb,'Maya Ortiz',NOW())`,[newId("policy"),JSON.stringify({checkout:["sandbox_only"],evidenceMinimum:"report_located"}),JSON.stringify({listingsEnabled:8,cartsAffected:0})]);
 await db.query(`INSERT INTO policy_versions(id,version,name,status,rules,impact_summary,created_by) VALUES($1,13,'Evidence recency proposal','draft',$2::jsonb,$3::jsonb,'Maya Ortiz')`,[newId("policy"),JSON.stringify({maximumReportAgeDays:180}),JSON.stringify({listingsDisabled:3,sellersAffected:2,openCartsAffected:1})]);
 for(const f of [["checkout","checkout:demo-1042",72,"high",["velocity","address_mismatch"],"open"],["review","review:cluster-7",58,"medium",["duplicate_language","shared_device"],"investigating"],["seller","seller:helix",31,"low",["inventory_spike"],"watching"]]) await db.query(`INSERT INTO fraud_cases(id,subject_type,subject_id,score,severity,signals,status) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7)`,[newId("fraud"),f[0],f[1],f[2],f[3],JSON.stringify(f[4]),f[5]]);
 const events=["search_performed","listing_viewed","evidence_opened","comparison_created","cart_created","checkout_started","order_completed"];for(let i=0;i<180;i++)await db.query(`INSERT INTO analytics_events(id,event_name,actor_key,properties,occurred_at) VALUES($1,$2,$3,$4::jsonb,NOW()-($5 || ' hours')::interval)`,[newId("event"),events[i%events.length],`visitor:${i%28}`,JSON.stringify({source:i%3===0?"organic":"direct",experiment:i%2?"control":"variant"}),String(i%72)]);
 for(const f of [["semantic_search_v2","Alias-aware ranking with explanation",true,100],["seller_health_panel","Expanded seller performance dimensions",true,50],["commerce_production","Real money movement hard stop",false,0]])await db.query(`INSERT INTO feature_flags(id,key,description,enabled,rollout_percent) VALUES($1,$2,$3,$4,$5)`,[newId("flag"),...f]);
 for(const e of [["catalog_extract","clerk-1.4","vendor-pages-golden",0.963,true,[]],["entity_resolution","resolver-1.2","aliases-edge-cases",0.927,true,["counterion ambiguity"]],["publication_audit","auditor-2.0","unsupported-claims",1,true,[]]])await db.query(`INSERT INTO agent_evaluations(id,workflow,version,dataset,score,pass,failures) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb)`,[newId("eval"),e[0],e[1],e[2],e[3],e[4],JSON.stringify(e[5])]);
 await db.query(`INSERT INTO privacy_requests(id,user_id,request_type,status,due_at,audit_notes) VALUES($1,'user:customer:nora','export','in_progress',NOW()+INTERVAL '21 days','Identity confirmed in sandbox.')`,[newId("privacy")]);
 await db.query(`INSERT INTO privacy_requests(id,user_id,request_type,status,due_at,audit_notes) VALUES($1,'user:seller:marcus','deletion','received',NOW()+INTERVAL '28 days','Awaiting dependency scan.')`,[newId("privacy")]);
 const seller=(await db.query<QueryResultRow&{id:string}>(`SELECT id FROM commerce_sellers ORDER BY id LIMIT 1`)).rows[0]?.id;if(seller){await db.query(`INSERT INTO seller_catalog_drafts(id,seller_id,name,compound,quantity_label,price,inventory,status,evidence_status) VALUES($1,$2,'BPC-157 Research Vial','BPC-157','10 mg',54,18,'review','current')`,[newId("draft"),seller]);await db.query(`INSERT INTO seller_catalog_drafts(id,seller_id,name,compound,quantity_label,price,inventory,status,evidence_status) VALUES($1,$2,'GHK-Cu Research Vial','GHK-Cu','50 mg',63,9,'draft','missing')`,[newId("draft"),seller]);await db.query(`INSERT INTO seller_team_members(id,seller_id,email,display_name,role,status) VALUES($1,$2,'marcus@helixtest.test','Marcus Vale','owner','active')`,[newId("member"),seller]);await db.query(`INSERT INTO seller_team_members(id,seller_id,email,display_name,role,status) VALUES($1,$2,'ops@helixtest.test','Ari Moss','operations','invited')`,[newId("member"),seller]);}
}
export async function ensureInternalOpsSeed(){if(!globalThis.__vialInternalSeedPromise)globalThis.__vialInternalSeedPromise=seedInternalOps().catch(error=>{globalThis.__vialInternalSeedPromise=undefined;throw error});return globalThis.__vialInternalSeedPromise}

const allowed=new Set(["internal_users","internal_notifications","support_cases","marketplace_reviews","policy_versions","fraud_cases","analytics_events","feature_flags","agent_evaluations","privacy_requests","scenario_runs","seller_catalog_drafts","seller_team_members"]);
export async function listRows(table:string,order="created_at DESC",limit=50){await ensureInternalOpsSeed();if(!allowed.has(table))throw new Error("Unsupported table");const db=await getDatabase();return (await db.query(`SELECT * FROM ${table} ORDER BY ${order} LIMIT $1`,[limit])).rows as Array<Record<string,unknown>>}
export async function runScenario(key:string,actor="administrator"){await ensureInternalOpsSeed();const db=await getDatabase();const defs:Record<string,{name:string;outputs:Record<string,unknown>}>= {price_drop:{name:"Price drop cascade",outputs:{listingUpdated:true,notifications:14,signalsRecomputed:3}},seller_suspension:{name:"Seller suspension",outputs:{listingsDisabled:4,openCartsFlagged:2,payoutHold:true}},dispute_spike:{name:"Dispute spike",outputs:{fraudCaseOpened:true,sellerHealth:"monitor",reserveIncrease:"5%"}},policy_change:{name:"Policy change simulation",outputs:{listingsDisabled:3,sellersAffected:2,notificationsQueued:11}}};const def=defs[key]??defs.price_drop;const id=newId("scenario");await db.query(`INSERT INTO scenario_runs(id,scenario_key,name,inputs,outputs,root_event_id,created_by) VALUES($1,$2,$3,$4::jsonb,$5::jsonb,$6,$7)`,[id,key,def.name,JSON.stringify({mode:"sandbox"}),JSON.stringify(def.outputs),newId("root"),actor]);return{id,...def}}
