import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { requireApiPrincipal } from "@/server/auth/principal";
import { createSavedSearch, deleteSavedSearch, listSavedSearches, updateSavedSearch } from "@/server/consumer-intelligence/repository";
import { savedSearchPatchSchema } from "@/server/consumer-intelligence/schemas";
import { runSavedSearch } from "@/server/consumer-intelligence/service";
import { isUniqueViolation } from "@/server/postgres-error";
const createSchema=z.object({name:z.string().trim().min(2).max(80),query:z.string().trim().min(1).max(240),filters:z.record(z.string(),z.unknown()).default({}),alertMode:z.enum(["off","important","all"]).default("important")});
export async function GET(request:NextRequest){const a=await requireApiPrincipal({accountTypes:["customer","seller"]});if(a.response)return a.response;const id=request.nextUrl.searchParams.get("run");if(id){const result=await runSavedSearch(a.principal.id,id);return result?NextResponse.json(result):NextResponse.json({error:"Saved search not found"},{status:404});}return NextResponse.json({searches:await listSavedSearches(a.principal.id)},{headers:{"cache-control":"private, no-store"}})}
export async function POST(request:Request){const a=await requireApiPrincipal({accountTypes:["customer","seller"]});if(a.response)return a.response;const parsed=createSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Invalid saved search",issues:parsed.error.flatten()},{status:400});try{return NextResponse.json(await createSavedSearch(a.principal.id,parsed.data),{status:201})}catch(error){if(isUniqueViolation(error))return NextResponse.json({error:"A saved search already uses that name"},{status:409});throw error}}
export async function PATCH(request:Request){const a=await requireApiPrincipal({accountTypes:["customer","seller"]});if(a.response)return a.response;const parsed=savedSearchPatchSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Invalid saved search update",issues:parsed.error.flatten()},{status:400});const{id,name,alertMode}=parsed.data;try{const updated=await updateSavedSearch(a.principal.id,id,{name,alertMode});return updated?NextResponse.json(updated,{headers:{"cache-control":"private, no-store"}}):NextResponse.json({error:"Saved search not found"},{status:404})}catch(error){if(isUniqueViolation(error))return NextResponse.json({error:"A saved search already uses that name"},{status:409});throw error}}
export async function DELETE(request:NextRequest){const a=await requireApiPrincipal({accountTypes:["customer","seller"]});if(a.response)return a.response;const id=request.nextUrl.searchParams.get("id");if(!id)return NextResponse.json({error:"Missing id"},{status:400});return NextResponse.json({deleted:await deleteSavedSearch(a.principal.id,id)})}
