#!/usr/bin/env node
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import * as z from "zod/v4";
import { getDatabase } from "../src/server/db/client";
import { newId } from "../src/server/db/ids";
import { authenticateLaboratoryApiToken, verifyCustodyChain } from "../src/server/evidence-network/repository";

async function main() {
  const rawToken = process.env.VIAL_MCP_LAB_TOKEN?.trim();
  if (!rawToken) { console.error("VIAL_MCP_LAB_TOKEN is required"); process.exit(1); }
  const authenticated = await authenticateLaboratoryApiToken(rawToken);
  if (!authenticated) { console.error("The laboratory MCP token is invalid, expired, or revoked"); process.exit(1); }
  const auth = authenticated;
  function requireScope(scope: string) { if (!auth.scopes.includes(scope)) throw new Error(`Token does not include ${scope}`); }
  function result(value: unknown) { return { content: [{ type: "text" as const, text: JSON.stringify(value, null, 2) }], structuredContent: value as Record<string, unknown> }; }
  async function proposal(type: string, subjectType: string, subjectId: string, payload: Record<string, unknown>) {
    const db = await getDatabase(); const id = newId("lab-proposal");
    await db.query(`INSERT INTO laboratory_work_proposals(id,laboratory_id,proposal_type,subject_type,subject_id,payload,status,created_by) VALUES($1,$2,$3,$4,$5,$6::jsonb,'pending',$7)`, [id, auth.laboratoryId, type, subjectType, subjectId, JSON.stringify(payload), `mcp:${auth.tokenId}`]);
    return { id, approvalRequired: true, status: "pending", authority: "proposal_only" };
  }
  const server = new McpServer({ name: "vial-laboratory", version: "6.0.0" });
  server.registerTool("get_lab_status", { description: "Read laboratory profile, onboarding, and workload counts.", inputSchema: {} }, async () => { requireScope("lab:read"); const db=await getDatabase(); const profile=await db.query(`SELECT id,display_name,status,onboarding_status,accreditation_status,accreditation_scope FROM laboratory_profiles WHERE id=$1`,[auth.laboratoryId]); const counts=await db.query(`SELECT (SELECT COUNT(*) FROM laboratory_test_orders WHERE laboratory_id=$1) orders,(SELECT COUNT(*) FROM laboratory_samples s JOIN laboratory_test_orders o ON o.id=s.test_order_id WHERE o.laboratory_id=$1) samples,(SELECT COUNT(*) FROM laboratory_reports WHERE laboratory_id=$1 AND status='issued') reports`,[auth.laboratoryId]); return result({profile:profile.rows[0]??null,counts:counts.rows[0]??{}}); });
  server.registerTool("list_test_orders", { description: "List the authenticated laboratory's test orders.", inputSchema: { status: z.string().optional() } }, async ({status}) => { requireScope("lab:read"); const db=await getDatabase(); const rows=await db.query(`SELECT id,order_number,status,priority,declared_batch_code,requested_dimensions,due_at FROM laboratory_test_orders WHERE laboratory_id=$1 AND ($2::text IS NULL OR status=$2) ORDER BY created_at DESC`,[auth.laboratoryId,status??null]); return result({orders:rows.rows}); });
  server.registerTool("list_methods", { description: "List method versions, scope, validation, and accreditation coverage.", inputSchema: {} }, async () => { requireScope("lab:read"); const db=await getDatabase(); const rows=await db.query(`SELECT id,method_code,name,version,technique,analytes,matrices,dimensions,validation_status,accreditation_covered FROM laboratory_methods WHERE laboratory_id=$1 ORDER BY technique,name`,[auth.laboratoryId]); return result({methods:rows.rows}); });
  server.registerTool("get_sample_custody", { description: "Read a sample's custody events and verify its hash chain.", inputSchema: { sampleId: z.string() } }, async ({sampleId}) => { requireScope("lab:read"); const db=await getDatabase(); const owned=(await db.query(`SELECT s.id FROM laboratory_samples s JOIN laboratory_test_orders o ON o.id=s.test_order_id WHERE s.id=$1 AND o.laboratory_id=$2`,[sampleId,auth.laboratoryId])).rows[0]; if(!owned)throw new Error("Sample not found"); const events=(await db.query(`SELECT sequence_number,event_type,actor_type,actor_id,location,occurred_at,event_hash,previous_event_hash FROM sample_custody_events WHERE sample_id=$1 ORDER BY sequence_number`,[sampleId])).rows; return result({events,verification:await verifyCustodyChain(sampleId,db)}); });
  server.registerTool("prepare_result_proposal", { description: "Create a structured analytical-result proposal. This cannot approve or publish a result.", inputSchema: { runId:z.string(), dimension:z.string(), analyte:z.string().optional(), resultType:z.enum(["numeric","categorical"]), valueNumeric:z.number().optional(), valueText:z.string().optional(), unit:z.string().optional(), conclusion:z.enum(["established","unknown","out_of_specification"]) } }, async (input) => { requireScope("lab:propose"); const db=await getDatabase(); const owned=(await db.query(`SELECT r.id FROM analytical_runs r JOIN laboratory_methods m ON m.id=r.method_id WHERE r.id=$1 AND m.laboratory_id=$2`,[input.runId,auth.laboratoryId])).rows[0]; if(!owned)throw new Error("Run not found"); return result(await proposal("analytical_result","run",input.runId,input)); });
  server.registerTool("prepare_report_draft", { description: "Prepare a report draft from reviewed results. This cannot issue, sign, amend, or revoke a report.", inputSchema: { testOrderId:z.string(), sampleId:z.string(), reportNumber:z.string(), summary:z.string() } }, async (input) => { requireScope("lab:propose"); const db=await getDatabase(); const owned=(await db.query(`SELECT o.id FROM laboratory_test_orders o JOIN laboratory_samples s ON s.test_order_id=o.id WHERE o.id=$1 AND s.id=$2 AND o.laboratory_id=$3`,[input.testOrderId,input.sampleId,auth.laboratoryId])).rows[0]; if(!owned)throw new Error("Order or sample not found"); const results=(await db.query(`SELECT ar.id,ar.dimension,ar.value_numeric,ar.value_text,ar.unit,ar.conclusion,ar.review_status FROM analytical_results ar JOIN analytical_runs r ON r.id=ar.run_id WHERE r.test_order_id=$1 AND r.sample_id=$2 ORDER BY ar.dimension`,[input.testOrderId,input.sampleId])).rows; return result({...await proposal("report_draft","sample",input.sampleId,{...input,results}),draft:{...input,results}}); });
  const transport=new StdioServerTransport(); await server.connect(transport); console.error("VIAL Laboratory MCP server ready on stdio");
}
main().catch(error=>{console.error(error instanceof Error?error.message:String(error));process.exit(1)});
