import type { Metadata } from "next";
import { Activity, BellRing, FileCheck2, GitBranch, GitPullRequestArrow, Lightbulb, RadioTower, Sparkles } from "lucide-react";
import Link from "next/link";
import { AgentRunTable } from "@/components/agent-run-table";
import { requireStaff } from "@/server/auth/session";
import { getRecentAgentRuns } from "@/server/catalog/repository";
import { getIntelligenceMetrics, getOpportunitySignals, getTraceRoots } from "@/server/intelligence/repository";
import { getRefreshMetrics } from "@/server/refresh/repository";
import { getAdminMetrics } from "@/server/review/repository";

export const metadata: Metadata = { title: "Operations overview" };
export const dynamic = "force-dynamic";

export default async function AdminOverviewPage() {
  await requireStaff();
  const [metrics, refresh, intelligence, runs, traces, opportunities] = await Promise.all([
    getAdminMetrics(), getRefreshMetrics(), getIntelligenceMetrics(), getRecentAgentRuns(8), getTraceRoots(3), getOpportunitySignals({ status: "open", limit: 3 }),
  ]);
  const cards = [
    { label: "Pending review", value: metrics.pendingClaims, icon: GitPullRequestArrow, href: "/admin/review", detail: "Atomic human decisions" },
    { label: "Controlled sources", value: refresh.enabled, icon: RadioTower, href: "/admin/sources", detail: `${refresh.queued} active queue items` },
    { label: "Causal traces", value: intelligence.traces, icon: GitBranch, href: "/admin/traces", detail: `${intelligence.alerts} generated alerts` },
    { label: "Open signals", value: intelligence.open, icon: Lightbulb, href: "/admin/opportunities", detail: "Compounding market insights" },
  ];
  return <div>
    <p className="text-[11px] font-extrabold uppercase tracking-[.18em] text-[#2b31d8]">Control plane</p>
    <div className="mt-3 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><h1 className="text-4xl font-extrabold tracking-[-.055em] sm:text-5xl">Market operations</h1><p className="mt-4 max-w-3xl text-sm font-medium leading-6 text-[var(--muted)]">VIAL now operates as a controlled intelligence system: sources refresh into immutable snapshots, claims wait for review, and approved changes cascade through metrics, alerts, histories, and second-order opportunity signals.</p></div><Link href="/admin/sources" className="ink hard-sm press inline-flex h-11 items-center justify-center gap-2 rounded-full bg-[#111214] px-5 text-sm font-bold text-white"><Activity className="size-4"/>Open refresh engine</Link></div>
    <div className="mt-9 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({label,value,icon:Icon,href,detail})=><Link key={label} href={href} className="group ink hard press rounded-[18px] bg-white p-5"><div className="flex items-center justify-between"><span className="ink-1 grid size-10 place-items-center rounded-[12px] bg-[#eef0ff]"><Icon className="size-4 text-[#2b31d8]"/></span><span className="text-xs font-bold text-[var(--muted)] group-hover:text-[#2b31d8]">Open →</span></div><p className="mt-7 text-4xl font-extrabold tabular-nums tracking-[-.06em]">{value}</p><p className="mt-2 text-sm font-bold">{label}</p><p className="mt-1 text-xs font-medium text-[var(--muted)]">{detail}</p></Link>)}</div>
    <section className="mt-10 grid gap-5 xl:grid-cols-[1.08fr_.92fr]"><div className="ink hard rounded-[20px] bg-white p-5 sm:p-7"><div className="flex items-center justify-between gap-4"><div><p className="text-[11px] font-extrabold uppercase tracking-[.16em] text-[#2b31d8]">Run ledger</p><h2 className="mt-2 text-2xl font-extrabold tracking-[-.035em]">Latest workflow receipts</h2></div><Link href="/admin/runs" className="text-sm font-bold text-[#2b31d8]">All runs</Link></div><div className="mt-6"><AgentRunTable runs={runs}/></div></div><div className="ink rounded-[20px] bg-[#111214] p-6 text-white"><div className="flex items-center justify-between"><div><p className="text-[11px] font-extrabold uppercase tracking-[.16em] text-[#8fa2ff]">Trace activity</p><h2 className="mt-2 text-2xl font-extrabold tracking-[-.035em]">Recent cascades</h2></div><GitBranch className="size-5 text-[#8fa2ff]"/></div><div className="mt-6 space-y-3">{traces.map(trace=><Link key={trace.id} href={`/admin/traces#${trace.id}`} className="block rounded-[12px] border border-white/25 bg-white/[.06] p-4 hover:bg-white/[.12]"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold">{trace.eventType}</p><p className="mt-1 font-mono text-[9px] text-white/30">{trace.id.slice(0,27)}</p></div><span className="rounded-full border border-white/25 bg-white/10 px-2 py-1 text-[9px] font-bold">{trace.events.length} events</span></div><div className="mt-3 flex gap-3 text-[10px] text-white/45"><span>{trace.alertCount} alerts</span><span>{trace.opportunityCount} signals</span></div></Link>)}{traces.length===0&&<p className="py-10 text-center text-sm text-white/45">No traces yet.</p>}</div></div></section>
    <section className="mt-6 grid gap-4 lg:grid-cols-3"><div className="ink hard rounded-[20px] bg-[#f0edff] p-6"><Sparkles className="size-5 text-[#2b31d8]"/><h2 className="mt-7 text-2xl font-extrabold tracking-[-.04em]">One change compounds.</h2><p className="mt-3 text-sm font-medium leading-6 text-[var(--muted)]">A batch update can also create a change alert, reopen an evidence gap, recalculate compound coverage, update vendor history, and reveal a new market signal.</p></div>{opportunities.slice(0,2).map(signal=><Link href="/admin/opportunities" key={signal.id} className="ink hard press rounded-[20px] bg-white p-6"><div className="flex items-center justify-between"><Lightbulb className="size-5 text-[#2b31d8]"/><span className="text-3xl font-extrabold tracking-[-.05em] tabular-nums">{Math.round(signal.score)}</span></div><p className="mt-7 text-[10px] font-extrabold uppercase tracking-[.14em] text-[var(--muted)]">{signal.signalType.replaceAll("-"," ")}</p><h2 className="mt-2 text-lg font-extrabold tracking-[-.025em]">{signal.title}</h2><p className="mt-2 text-xs font-medium leading-5 text-[var(--muted)]">{signal.summary}</p></Link>)}</section>
    <section className="mt-6 grid gap-4 lg:grid-cols-3"><Info icon={FileCheck2} title="Human publication" text={`${metrics.publications} versioned receipts preserve before and after state.`}/><Info icon={BellRing} title="Watchlist alerts" text="Only reviewed publications generate public change notifications."/><Info icon={RadioTower} title="Bounded refresh" text={`${refresh.stale} enabled sources currently need a successful refresh within 24 hours.`}/></section>
  </div>;
}
function Info({icon:Icon,title,text}:{icon:React.ComponentType<{className?:string}>;title:string;text:string}){return <div className="ink hard rounded-[18px] bg-white p-5"><Icon className="size-4 text-[#2b31d8]"/><h2 className="mt-5 text-sm font-bold">{title}</h2><p className="mt-2 text-xs font-medium leading-5 text-[var(--muted)]">{text}</p></div>}
