export const foundationSchemaSql=String.raw`
CREATE TABLE IF NOT EXISTS schema_migrations(version INTEGER PRIMARY KEY,name TEXT NOT NULL,applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS auth_users(id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE,display_name TEXT NOT NULL,account_type TEXT NOT NULL,roles JSONB NOT NULL DEFAULT '[]'::jsonb,status TEXT NOT NULL DEFAULT 'active',email_verified_at TIMESTAMPTZ,mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE,last_login_at TIMESTAMPTZ,locked_until TIMESTAMPTZ,failed_login_count INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS auth_credentials(user_id TEXT PRIMARY KEY REFERENCES auth_users(id) ON DELETE CASCADE,password_hash TEXT NOT NULL,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS auth_sessions(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES auth_users(id) ON DELETE CASCADE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),expires_at TIMESTAMPTZ NOT NULL,revoked_at TIMESTAMPTZ,revocation_reason TEXT,request_id TEXT,ip_hash TEXT,user_agent_hash TEXT);
CREATE TABLE IF NOT EXISTS auth_login_attempts(id TEXT PRIMARY KEY,normalized_email TEXT NOT NULL,outcome TEXT NOT NULL,request_id TEXT,ip_hash TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS security_audit_events(id TEXT PRIMARY KEY,event_type TEXT NOT NULL,outcome TEXT NOT NULL DEFAULT 'success',actor_type TEXT NOT NULL DEFAULT 'system',actor_id TEXT,target_type TEXT,target_id TEXT,request_id TEXT,ip_hash TEXT,metadata JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS security_rate_limits(bucket TEXT NOT NULL,key_hash TEXT NOT NULL,window_started_at TIMESTAMPTZ NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,blocked_until TIMESTAMPTZ,PRIMARY KEY(bucket,key_hash));
CREATE TABLE IF NOT EXISTS user_watchlists(user_id TEXT NOT NULL REFERENCES auth_users(id) ON DELETE CASCADE,listing_slug TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY(user_id,listing_slug));
CREATE TABLE IF NOT EXISTS user_notification_preferences(user_id TEXT PRIMARY KEY REFERENCES auth_users(id) ON DELETE CASCADE,in_app_enabled BOOLEAN NOT NULL DEFAULT TRUE,email_enabled BOOLEAN NOT NULL DEFAULT FALSE,price_alerts BOOLEAN NOT NULL DEFAULT TRUE,evidence_alerts BOOLEAN NOT NULL DEFAULT TRUE,order_alerts BOOLEAN NOT NULL DEFAULT TRUE,digest_frequency TEXT NOT NULL DEFAULT 'instant',updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS operational_metric_snapshots(id TEXT PRIMARY KEY,metric_key TEXT NOT NULL,value NUMERIC NOT NULL,dimensions JSONB NOT NULL DEFAULT '{}'::jsonb,observed_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS operational_alerts(id TEXT PRIMARY KEY,alert_key TEXT NOT NULL UNIQUE,severity TEXT NOT NULL,title TEXT NOT NULL,summary TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',details JSONB NOT NULL DEFAULT '{}'::jsonb,opened_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),resolved_at TIMESTAMPTZ);
CREATE INDEX IF NOT EXISTS idx_auth_sessions_user ON auth_sessions(user_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_auth_attempts_email ON auth_login_attempts(normalized_email,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_security_audit_created ON security_audit_events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_operational_alerts_status ON operational_alerts(status,severity,updated_at DESC);
`;
