"use client";
import { formatCurrency } from "@/lib/format";
import type { Product } from "@/lib/types";
import { Check, Minus, X } from "lucide-react";
import Link from "next/link";
import { useMarketplace } from "./marketplace-state";
import { ProductVisual } from "./product-visual";
export function CompareClient(){const{catalog,compare,toggleCompare}=useMarketplace();const{products,vendors}=catalog;const selected=compare.length>0?compare.map(slug=>products.find(item=>item.slug===slug)).filter((item):item is Product=>Boolean(item)):products.filter(item=>item.featured).slice(0,3);const examples=compare.length===0;return <div>{examples&&<div className="mb-6 rounded-2xl border border-violet-200 bg-violet-50 px-4 py-3 text-sm text-violet-800">Showing an example comparison. Add listings from the market to create your own.</div>}<div className="overflow-x-auto pb-3"><div className="grid min-w-[860px] gap-px overflow-hidden rounded-[28px] border border-black/[.07] bg-black/[.07]" style={{gridTemplateColumns:`190px repeat(${selected.length}, minmax(220px, 1fr))`}}><div className="bg-[#f7f7f4] p-5"/>{selected.map(product=>{const vendor=vendors.find(item=>item.slug===product.vendorSlug);return <div key={product.slug} className="relative bg-white p-4">{!examples&&<button onClick={()=>toggleCompare(product.slug)} className="absolute right-3 top-3 z-10 grid size-8 place-items-center rounded-full border border-black/[.08] bg-white/80" aria-label={`Remove ${product.name} from comparison`}><X className="size-3.5"/></button>}<ProductVisual name={product.name} quantity={product.quantity} accent={product.accent} compact/><div className="px-1 pb-2 pt-4"><Link href={`/products/${product.slug}`} className="text-lg font-semibold tracking-[-0.03em] hover:underline">{product.name} {product.quantity}</Link><p className="mt-1 text-sm text-[var(--muted)]">{vendor?.name}</p><p className="mt-3 text-2xl font-semibold tracking-[-0.04em]">{formatCurrency(product.price)}</p></div></div>})}<CompareRow label="Evidence level" values={selected.map(i=>i.evidenceLabel)}/><CompareRow label="Report date" values={selected.map(i=>i.reportDate)}/><CompareRow label="Issuer confirmed" values={selected.map(i=>i.reportConfirmed)}/><CompareRow label="Batch linked" values={selected.map(i=>i.batchLinked)}/><CompareRow label="Sample origin" values={selected.map(i=>i.sampleOrigin)}/><CompareRow label="Availability" values={selected.map(i=>i.availability)}/><CompareRow label="Shipping" values={selected.map(i=>i.shipping)}/><CompareRow label="Rating" values={selected.map(i=>`${i.rating} / 5 (${i.reviewCount})`)}/><CompareRow label="Checkout" values={selected.map(i=>i.checkoutMode==="marketplace-pending"?"Pending eligibility":"Information only")}/></div></div><div className="mt-8 flex flex-wrap items-center gap-3"><Link href="/market" className="rounded-full bg-black px-5 py-3 text-sm font-semibold text-white">Add from market</Link>{!examples&&<p className="text-sm text-[var(--muted)]">Select up to four listings. Adding a fifth replaces the oldest selection.</p>}</div></div>}
function CompareRow({label,values}:{label:string;values:Array<string|boolean>}){return <><div className="bg-[#f7f7f4] p-5 text-sm font-semibold">{label}</div>{values.map((value,index)=><div key={`${label}-${index}`} className="flex items-center bg-white p-5 text-sm text-black/75">{typeof value==="boolean"?(value?<span className="inline-flex items-center gap-1.5 font-semibold text-emerald-700"><Check className="size-4"/> Yes</span>:<span className="inline-flex items-center gap-1.5 text-[var(--muted)]"><Minus className="size-4"/> No</span>):value}</div>)}</>}
