import Link from "next/link";
import { Wordmark } from "./wordmark";

const groups = [
  { title: "Explore", links: [["Market","/market"],["Compounds","/compounds"],["Vendors","/vendors"],["Compare","/compare"],["What's moving","/signals"],["Saved","/watchlist"]] },
  { title: "How we check", links: [["How we check","/how-we-check"],["Purity vs grade","/grades"],["Batch test records","/passports"],["Lab reports","/research"],["Independent testing","/testing"],["Laboratories","/labs"],["Enforcement record","/enforcement"],["System status","/status"]] },
  { title: "Company", links: [["About","/about"],["Help center","/help"],["Account","/account"]] },
  { title: "Legal", links: [["US law & regulations","/legal/us-regulations"],["Privacy","/legal/privacy"],["Terms","/legal/terms"],["Disclaimer","/legal/disclaimer"],["Contact & corrections","/legal/contact"],["Limitations","/how-we-check#limitations"]] },
];
export function SiteFooter({hasDemo=false}:{hasDemo?:boolean}){return <footer className="border-t-2 border-[#111214] bg-[#111214] text-white"><div className="mx-auto max-w-[1320px] px-5 py-12 sm:px-8 sm:py-16"><div className="grid gap-12 lg:grid-cols-[1.2fr_2fr]"><div><Wordmark inverse idPrefix="wmf"/><p className="mt-5 max-w-sm text-sm leading-6 text-white/55">Every vendor&rsquo;s price, lab test, and reputation on one screen. {hasDemo?<>Records are demo unless marked <span className="font-bold text-[#8fffd6]">Live</span>, in which case they&rsquo;re aggregated from a real public source.</>:<>Every record is marked <span className="font-bold text-[#8fffd6]">Live</span> &mdash; aggregated from a real public source.</>} Either way, a listing is never an endorsement.</p></div><div className="grid grid-cols-2 gap-8 sm:grid-cols-4">{groups.map(group=><div key={group.title}><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-white/45">{group.title}</p><div className="mt-4 grid gap-3 text-sm font-medium text-white/65">{group.links.map(([label,href])=><Link key={href} href={href} className="w-fit transition hover:text-[#8fffd6]">{label}</Link>)}</div></div>)}</div></div><div className="mt-12 flex flex-col gap-3 border-t border-white/12 pt-6 text-xs leading-5 text-white/50 sm:flex-row sm:items-center sm:justify-between"><p>© 2026 VialGrade. Not a pharmacy, laboratory, or medical service.</p><p>Information only. VialGrade doesn&rsquo;t sell anything — when buying is real, we link you to the vendor&rsquo;s own site.</p></div></div></footer>}
