import Link from "next/link";
import { Wordmark } from "./wordmark";

const groups = [
  { title: "Explore", links: [["Market","/market"],["Compounds","/compounds"],["Vendors","/vendors"],["Compare","/compare"],["Signals","/signals"],["Batch passports","/passports"]] },
  { title: "Intelligence", links: [["Evidence library","/research"],["Laboratory network","/labs"],["Independent testing","/testing"],["Market updates","/updates"],["Watchlist","/watchlist"],["Operations","/operations"],["System status","/status"]] },
  { title: "Company", links: [["About","/about"],["Sell on VIAL","/sell"],["Methodology","/methodology"],["Help center","/help"],["Account","/account"],["Staff access","/admin"]] },
  { title: "Legal", links: [["Privacy","/legal/privacy"],["Terms","/legal/terms"],["Disclaimer","/legal/disclaimer"],["Limitations","/methodology#limitations"],["Governance","/methodology#governance"]] },
];
export function SiteFooter(){return <footer className="mt-24 border-t border-black/[.07] bg-[#111214] text-white"><div className="mx-auto max-w-[1320px] px-5 py-12 sm:px-8 sm:py-16"><div className="grid gap-12 lg:grid-cols-[1.2fr_2fr]"><div><Wordmark inverse/><p className="mt-5 max-w-sm text-sm leading-6 text-white/55">VIAL is an evidence-first market intelligence prototype. All vendors, laboratories, listings, prices, batches, ratings, and reviews are fictional demo data.</p></div><div className="grid grid-cols-2 gap-8 sm:grid-cols-4">{groups.map(group=><div key={group.title}><p className="text-xs font-semibold uppercase tracking-[0.16em] text-white/45">{group.title}</p><div className="mt-4 grid gap-3 text-sm text-white/65">{group.links.map(([label,href])=><Link key={href} href={href} className="hover:text-white">{label}</Link>)}</div></div>)}</div></div><div className="mt-12 flex flex-col gap-3 border-t border-white/10 pt-6 text-xs leading-5 text-white/50 sm:flex-row sm:items-center sm:justify-between"><p>© 2026 VIAL prototype. Not a pharmacy, laboratory, or medical service.</p><p>Information only. Commerce is a fictional test-mode simulation; no real funds or products move.</p></div></div></footer>}
