import Link from "next/link";
import { Wordmark } from "./wordmark";

const groups = [
  { title: "Explore", links: [["Market","/market"],["Compounds","/compounds"],["Vendors","/vendors"],["Compare","/compare"],["What's moving","/signals"],["Saved","/watchlist"]] },
  { title: "How we check", links: [["How we check","/how-we-check"],["Batch passports","/passports"],["Lab reports","/research"],["Independent testing","/testing"],["Laboratories","/labs"],["Change ledger","/updates"],["Provenance","/operations"],["System status","/status"]] },
  { title: "Company", links: [["About","/about"],["For vendors","/sell"],["Help center","/help"],["Developers","/developers"],["Account","/account"],["Staff access","/admin"]] },
  { title: "Legal", links: [["US law & regulations","/legal/us-regulations"],["Privacy","/legal/privacy"],["Terms","/legal/terms"],["Disclaimer","/legal/disclaimer"],["Limitations","/how-we-check#limitations"]] },
];
export function SiteFooter(){return <footer className="mt-24 border-t border-black/[.07] bg-[#111214] text-white"><div className="mx-auto max-w-[1320px] px-5 py-12 sm:px-8 sm:py-16"><div className="grid gap-12 lg:grid-cols-[1.2fr_2fr]"><div><Wordmark inverse/><p className="mt-5 max-w-sm text-sm leading-6 text-white/55">Every vendor&rsquo;s price, lab test, and reputation on one screen. Records are demo unless marked <span className="font-semibold text-emerald-300">Live</span>, in which case they&rsquo;re aggregated from a real public source. Either way, a listing is never an endorsement.</p></div><div className="grid grid-cols-2 gap-8 sm:grid-cols-4">{groups.map(group=><div key={group.title}><p className="text-xs font-semibold uppercase tracking-[0.16em] text-white/45">{group.title}</p><div className="mt-4 grid gap-3 text-sm text-white/65">{group.links.map(([label,href])=><Link key={href} href={href} className="hover:text-white">{label}</Link>)}</div></div>)}</div></div><div className="mt-12 flex flex-col gap-3 border-t border-white/10 pt-6 text-xs leading-5 text-white/50 sm:flex-row sm:items-center sm:justify-between"><p>© 2026 VIAL. Not a pharmacy, laboratory, or medical service.</p><p>Information only. VIAL doesn&rsquo;t sell anything — when buying is real, we link you to the vendor&rsquo;s own site.</p></div></div></footer>}
