import type { QueryResultRow } from "pg";
import { getDatabase, type SqlConnection } from "@/server/db/client";
import { newId } from "@/server/db/ids";

function scoreReliability(input:{fetch:number;precision:number;correction:number;latency:number}){
  const latencyScore=Math.max(0,1-Math.max(0,input.latency-1000)/9000);
  return Math.max(0,Math.min(1,input.fetch*0.35+input.precision*0.4+(1-input.correction)*0.2+latencyScore*0.05));
}

export async function seedFreshnessPolicies(connection?:SqlConnection){const db=connection??await getDatabase();const rows=[
 ["fresh:listing:price","listing","price",60,360,1440],
 ["fresh:listing:availability","listing","availability",60,240,720],
 ["fresh:listing:batch","listing","batchCode",1440,4320,10080],
 ["fresh:listing:report","listing","reportDate",10080,43200,86400],
 ["fresh:source:health","source","health",60,360,1440],
 ];for(const row of rows)await db.query(`INSERT INTO freshness_policies(id,subject_type,predicate,warning_age_minutes,stale_age_minutes,critical_age_minutes,policy_version,active) VALUES($1,$2,$3,$4,$5,$6,1,TRUE) ON CONFLICT(subject_type,predicate,policy_version) DO UPDATE SET warning_age_minutes=EXCLUDED.warning_age_minutes,stale_age_minutes=EXCLUDED.stale_age_minutes,critical_age_minutes=EXCLUDED.critical_age_minutes,active=TRUE`,row);}

export async function recomputeFreshness(connection?:SqlConnection){const db=connection??await getDatabase();const policies=(await db.query<QueryResultRow & {id:string;predicate:string;warning_age_minutes:number;stale_age_minutes:number;critical_age_minutes:number}>(`SELECT * FROM freshness_policies WHERE subject_type='listing' AND active=TRUE`)).rows;const listings=(await db.query<QueryResultRow & {id:string;source_id:string|null;updated_at:string;observed_at:string}>(`SELECT id,source_id,updated_at,observed_at FROM listings`)).rows;let updated=0;for(const listing of listings){for(const policy of policies){const latest=await db.query<QueryResultRow & {published_at:string|null;created_at:string}>(`SELECT published_at,created_at FROM evidence_claims WHERE subject_type='listing' AND subject_id=$1 AND predicate=$2 AND review_status='approved' ORDER BY COALESCE(published_at,created_at) DESC LIMIT 1`,[listing.id,policy.predicate]);const verifiedAt=new Date(latest.rows[0]?.published_at??latest.rows[0]?.created_at??listing.observed_at??listing.updated_at);const age=Math.max(0,Math.floor((Date.now()-verifiedAt.getTime())/60000));const status=age>=policy.critical_age_minutes?'critical':age>=policy.stale_age_minutes?'stale':age>=policy.warning_age_minutes?'warning':'current';const nextDue=new Date(verifiedAt.getTime()+policy.warning_age_minutes*60000);await db.query(`INSERT INTO data_freshness_status(id,subject_type,subject_id,predicate,source_id,last_verified_at,next_due_at,status,age_minutes,policy_id,updated_at) VALUES($1,'listing',$2,$3,$4,$5,$6,$7,$8,$9,NOW()) ON CONFLICT(subject_type,subject_id,predicate) DO UPDATE SET source_id=EXCLUDED.source_id,last_verified_at=EXCLUDED.last_verified_at,next_due_at=EXCLUDED.next_due_at,status=EXCLUDED.status,age_minutes=EXCLUDED.age_minutes,policy_id=EXCLUDED.policy_id,updated_at=NOW()`,[`fresh:${listing.id}:${policy.predicate}`,listing.id,policy.predicate,listing.source_id,verifiedAt.toISOString(),nextDue.toISOString(),status,age,policy.id]);updated+=1;}}
 return {updated};}

export async function recomputeSourceReliability(connection?:SqlConnection){const db=connection??await getDatabase();const sources=(await db.query<QueryResultRow & {id:string}>(`SELECT id FROM sources`)).rows;const snapshots=[];for(const source of sources){const stats=await db.query<QueryResultRow & {attempts:string|number;successes:string|number;latency:string|number;claims:string|number;corrections:string|number}>(`SELECT COUNT(DISTINCT a.id) attempts,COUNT(DISTINCT a.id) FILTER(WHERE a.status='succeeded') successes,COALESCE(AVG(a.duration_ms),0) latency,COUNT(DISTINCT c.id) claims,COUNT(DISTINCT f.id) corrections FROM source_refresh_policies p LEFT JOIN refresh_jobs j ON j.policy_id=p.id LEFT JOIN refresh_attempts a ON a.job_id=j.id LEFT JOIN source_snapshots ss ON ss.source_id=p.source_id LEFT JOIN evidence_claims c ON c.source_snapshot_id=ss.id LEFT JOIN correction_feedback f ON f.claim_id=c.id WHERE p.source_id=$1`,[source.id]);const row=stats.rows[0];const attempts=Number(row?.attempts??0),successes=Number(row?.successes??0),claims=Number(row?.claims??0),corrections=Number(row?.corrections??0),latency=Number(row?.latency??0);const fetch=attempts?successes/attempts:1;const correction=claims?corrections/claims:0;const precision=Math.max(0,1-correction);const reliability=scoreReliability({fetch,precision,correction,latency});const id=newId('reliability');await db.query(`INSERT INTO source_reliability_snapshots(id,source_id,window_label,fetch_success_rate,extraction_precision,correction_rate,median_latency_ms,reliability_score,details) VALUES($1,$2,'all-time',$3,$4,$5,$6,$7,$8::jsonb)`,[id,source.id,fetch,precision,correction,latency,reliability,JSON.stringify({attempts,successes,claims,corrections})]);snapshots.push({sourceId:source.id,reliability,fetch,precision,correction,latency});}return snapshots;}

export async function recordCorrection(input:{subjectType:string;subjectId:string;claimId?:string;type:string;previousValue:unknown;correctedValue:unknown;reason:string;reviewer:string;impact?:string}){const db=await getDatabase();const id=newId('correction');await db.query(`INSERT INTO correction_feedback(id,subject_type,subject_id,claim_id,correction_type,previous_value,corrected_value,reason,reviewer,impact,status) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb,$8,$9,$10,'accepted')`,[id,input.subjectType,input.subjectId,input.claimId??null,input.type,JSON.stringify(input.previousValue),JSON.stringify(input.correctedValue),input.reason,input.reviewer,input.impact??'standard']);return id;}

export async function getDataQualityDashboard(){const db=await getDatabase();const [freshness,reliability,corrections,pilots]=await Promise.all([
 db.query<QueryResultRow & {status:string;count:string|number}>(`SELECT status,COUNT(*) count FROM data_freshness_status GROUP BY status ORDER BY status`),
 db.query<QueryResultRow & {source_id:string;label:string;reliability_score:number;fetch_success_rate:number;extraction_precision:number;correction_rate:number;median_latency_ms:number;observed_at:string}>(`SELECT DISTINCT ON(r.source_id) r.*,s.label FROM source_reliability_snapshots r JOIN sources s ON s.id=r.source_id ORDER BY r.source_id,r.observed_at DESC`),
 db.query<QueryResultRow & {count:string|number}>(`SELECT COUNT(*) count FROM correction_feedback WHERE status='accepted'`),
 db.query<QueryResultRow & {program_status:string;count:string|number}>(`SELECT program_status,COUNT(*) count FROM source_pilots GROUP BY program_status`),
 ]);return {freshness:freshness.rows.map(r=>({status:r.status,count:Number(r.count)})),reliability:reliability.rows.map(r=>({...r,reliability_score:Number(r.reliability_score),fetch_success_rate:Number(r.fetch_success_rate),extraction_precision:Number(r.extraction_precision),correction_rate:Number(r.correction_rate),median_latency_ms:Number(r.median_latency_ms)})),corrections:Number(corrections.rows[0]?.count??0),pilots:pilots.rows.map(r=>({status:r.program_status,count:Number(r.count)}))};}
