import { FileCheck2, Link2 } from "lucide-react";
import { SellerPageHeader, Panel, StatusPill, primaryButton, secondaryButton } from "@/components/seller/seller-ui";
import { requireSellerPermission } from "@/server/auth/session";
import { getSellerContext } from "@/server/seller/ops";
import { createEvidenceAction, reviewEvidenceLinkAction } from "../actions";

export default async function SellerEvidencePage() {
  const principal = await requireSellerPermission("seller:profile:read");
  const context = await getSellerContext(principal.email);
  if (!context) return null;
  return <>
    <SellerPageHeader title="Evidence workspace" description="Upload document metadata, extract structured fields, and review proposed product and batch relationships. Uploading never confirms a physical product claim." />
    <div className="mt-7 grid gap-6 xl:grid-cols-[.8fr_1.2fr]">
      <Panel title="Add evidence metadata" description="The sandbox stores metadata and a deterministic hash, not real document bytes."><form action={createEvidenceAction} className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium sm:col-span-2">Filename<input className="field mt-2" name="filename" required placeholder="batch-2607-coa.pdf" /></label><label className="text-sm font-medium">Type<select className="field mt-2" name="documentType"><option value="coa">Certificate of analysis</option><option value="sterility">Sterility report</option><option value="endotoxin">Endotoxin report</option><option value="identity">Identity report</option></select></label><label className="text-sm font-medium">Issuer<input className="field mt-2" name="issuer" /></label><label className="text-sm font-medium">Report ID<input className="field mt-2" name="reportIdentifier" /></label><label className="text-sm font-medium">Report date<input className="field mt-2" type="date" name="reportDate" /></label><label className="text-sm font-medium">Expires<input className="field mt-2" type="date" name="expiresAt" /></label><label className="text-sm font-medium">Identity<input className="field mt-2" name="identity" placeholder="BPC-157" /></label><label className="text-sm font-medium">Quantity<input className="field mt-2" name="quantity" placeholder="10 mg" /></label><label className="text-sm font-medium">Batch code<input className="field mt-2" name="batchCode" /></label><label className="flex items-center gap-2 self-end text-sm"><input type="checkbox" name="reportConfirmed" />Issuer confirmation claimed</label><label className="text-sm font-medium sm:col-span-2">Public source URL<input className="field mt-2" type="url" name="sourceUrl" /></label><button className={`${primaryButton} sm:col-span-2 sm:w-fit`}>Upload metadata and propose links</button></form></Panel>
      <div className="space-y-6"><Panel title="Documents" description={`${context.documents.length} evidence records`}>{context.documents.length ? <div className="space-y-3">{context.documents.map((row) => { const doc = row as Record<string, unknown>; return <div key={String(doc.id)} className="ink-1 flex items-start gap-4 rounded-[14px] bg-[#fafaf7] p-4"><div className="ink-1 grid size-10 place-items-center rounded-[10px] bg-white"><FileCheck2 className="size-4" /></div><div className="min-w-0 flex-1"><p className="truncate font-bold">{String(doc.filename)}</p><p className="mt-1 text-xs font-medium text-[var(--muted)]">{String(doc.issuer || "Issuer unknown")} · {String(doc.report_date || "Undated")}</p></div><StatusPill status={String(doc.status)} /></div>; })}</div> : <p className="text-sm font-medium text-[var(--muted)]">No evidence uploaded.</p>}</Panel>
      <Panel title="Proposed relationships" description="Confirm only when the document, product, and batch relationship is correct.">{context.evidenceLinks.length ? <div className="space-y-3">{context.evidenceLinks.map((row) => { const link = row as Record<string, unknown>; const reasons = Array.isArray(link.reasons) ? link.reasons as string[] : []; return <div key={String(link.id)} className="ink-1 rounded-[14px] p-4"><div className="flex items-start gap-3"><Link2 className="mt-0.5 size-4 text-[#6d5dfc]" /><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-bold">{String(link.filename)} → {String(link.product_title || "Unassigned")}</p><StatusPill status={String(link.status)} /></div><p className="mt-1 text-xs font-medium text-[var(--muted)]">{String(link.batch_code || "No batch")} · {Math.round(Number(link.confidence || 0) * 100)}% relationship confidence</p><p className="mt-2 text-xs text-[var(--muted)]">{reasons.join(" · ")}</p></div></div>{String(link.status) === "proposed" && <div className="mt-4 flex gap-2"><form action={reviewEvidenceLinkAction}><input type="hidden" name="linkId" value={String(link.id)} /><input type="hidden" name="status" value="confirmed" /><button className={primaryButton}>Confirm link</button></form><form action={reviewEvidenceLinkAction}><input type="hidden" name="linkId" value={String(link.id)} /><input type="hidden" name="status" value="rejected" /><button className={secondaryButton}>Reject</button></form></div>}</div>; })}</div> : <p className="text-sm font-medium text-[var(--muted)]">No proposed links.</p>}</Panel></div>
    </div>
  </>;
}
