import type { Metadata } from "next";
import { ArrowRight, Building2, FileCheck2, Network } from "lucide-react";
import Link from "next/link";
import { vendorStatusLabel } from "@/lib/format";
import { VendorMark } from "@/components/vendor-mark";
import { DataOriginBadge } from "@/components/data-origin-badge";
import { getCatalogSnapshot } from "@/server/catalog/repository";

export const metadata: Metadata = { title: "Vendor directory", description: "Browse persistent vendor profiles and observed market histories." };
export const dynamic = "force-dynamic";
export default async function VendorsPage(){const {vendors}=await getCatalogSnapshot(); return <div className="mx-auto max-w-[1320px] px-5 py-16 sm:px-8 sm:py-24"><div className="max-w-4xl"><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-[var(--muted)]">Vendor directory</p><h1 className="mt-4 text-5xl font-semibold tracking-[-.065em] sm:text-7xl">A vendor&rsquo;s real track record.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-[var(--muted)]">A shady seller can spin up a new website overnight. We keep the history &mdash; prices, tests, and changes &mdash; so a fresh coat of paint can&rsquo;t hide the record.</p></div><div className="mt-10 grid gap-3 sm:grid-cols-3"><Metric icon={Building2} value={String(vendors.length)} label="Observed profiles"/><Metric icon={FileCheck2} value={`${Math.round(vendors.reduce((s,v)=>s+v.documentationCurrent,0)/Math.max(vendors.length,1))}%`} label="Avg. tests current"/><Metric icon={Network} value={String(vendors.filter(v=>v.profileStatus!=="unclaimed").length)} label="Claimed or participating"/></div><div className="mt-12 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{vendors.map(vendor=><Link key={vendor.slug} href={`/vendors/${vendor.slug}`} className="group rounded-[30px] border border-black/[.07] bg-white p-6 transition hover:-translate-y-1 hover:shadow-[0_24px_70px_rgba(17,18,20,.09)]"><div className="flex items-start gap-4"><VendorMark initials={vendor.initials} accent={vendor.accent}/><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-semibold tracking-[-.035em]">{vendor.name}</h2>{vendor.origin==="live" && <DataOriginBadge origin="live"/>}</div><p className="mt-1 text-xs text-[var(--muted)]">{vendorStatusLabel(vendor.profileStatus)}{vendor.location?` · ${vendor.location}`:""}</p></div><ArrowRight className="size-4 text-black/25 transition group-hover:translate-x-1 group-hover:text-black"/></div></div></div><p className="mt-5 line-clamp-3 text-sm leading-6 text-[var(--muted)]">{vendor.description}</p><div className="mt-7 grid grid-cols-3 gap-2 border-t border-black/[.06] pt-5"><Mini value={String(vendor.productCount)} label="Products"/><Mini value={`${vendor.documentationCurrent}%`} label="Tests current"/><Mini value={String(vendor.history.length)} label="Observed events"/></div><div className="mt-5 rounded-2xl bg-[var(--background)] p-4"><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-[var(--muted)]">Latest observed event</p><p className="mt-2 text-xs leading-5">{vendor.history.at(-1)?.event ?? "No recorded history yet."}</p></div></Link>)}</div></div>}
function Metric({icon:Icon,value,label}:{icon:React.ComponentType<{className?:string}>;value:string;label:string}){return <div className="rounded-[22px] border border-black/[.07] bg-white p-5"><Icon className="size-4 text-black/30"/><p className="mt-5 text-3xl font-semibold tracking-[-.055em]">{value}</p><p className="mt-1 text-xs text-[var(--muted)]">{label}</p></div>}
function Mini({value,label}:{value:string;label:string}){return <div><p className="text-sm font-semibold tabular-nums">{value}</p><p className="mt-1 text-[10px] text-[var(--muted)]">{label}</p></div>}
