import type { Metadata } from "next";
import { Bell, BrainCircuit, GitCompareArrows, History, Search, Sparkles, Telescope, Users } from "lucide-react";
import { requirePermission } from "@/server/auth/session";
import { getConsumerIntelligenceDashboard } from "@/server/consumer-intelligence/repository";
export const metadata:Metadata={title:"Consumer intelligence"};
export const dynamic="force-dynamic";
export default async function Page(){await requirePermission("privacy:read");const data=await getConsumerIntelligenceDashboard();return <div><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-[var(--muted)]">Consumer intelligence</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.055em] sm:text-5xl">Personalization without hidden intent.</h1><p className="mt-4 max-w-3xl text-sm leading-6 text-[var(--muted)]">Aggregate operating metrics for saved searches, comparisons, follows, summaries, and relevance-ranked notifications. Individual user content remains access controlled.</p><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Users} value={data.personalizedUsers} label="personalized users"/><Metric icon={Search} value={data.savedSearches} label="active saved searches"/><Metric icon={GitCompareArrows} value={data.comparisons} label="comparison sessions"/><Metric icon={Bell} value={data.unread} label="unread notifications"/></div><div className="mt-6 grid gap-5 lg:grid-cols-3"><Panel icon={BrainCircuit} title="Home-view distribution">{data.homeViews.map(item=><Row key={item.view} label={item.view.replace("-"," ")} value={item.count}/>)}</Panel><Panel icon={Telescope} title="Most-followed entities">{data.topFollows.map(item=><Row key={`${item.entityType}:${item.entitySlug}`} label={`${item.entityType} · ${item.entitySlug}`} value={item.count}/>)}</Panel><Panel icon={History} title="Decision events · 30 days">{data.recentEvents.map(item=><Row key={item.eventType} label={item.eventType.replace(/_/g," ")} value={item.count}/>)}</Panel></div><section className="mt-6 rounded-[28px] bg-[#111214] p-6 text-white"><div className="grid gap-6 sm:grid-cols-3"><Stat icon={Sparkles} value={data.summaries} label="change summaries"/><Stat icon={Bell} value={data.notifications} label="notifications generated"/><Stat icon={BrainCircuit} value={`${Math.round(data.averageRelevance*100)}%`} label="average relevance"/></div><p className="mt-6 text-xs leading-5 text-white/40">Relevance is an explicit market-information score based on user-selected interests. It is not a medical, suitability, or safety score.</p></section></div>}
function Metric({icon:Icon,value,label}:{icon:React.ComponentType<{className?:string}>;value:number;label:string}){return <div className="rounded-[24px] border border-black/[.07] bg-white p-5"><Icon className="size-4 text-black/35"/><p className="mt-6 text-4xl font-semibold">{value}</p><p className="mt-1 text-xs text-[var(--muted)]">{label}</p></div>}
function Panel({icon:Icon,title,children}:{icon:React.ComponentType<{className?:string}>;title:string;children:React.ReactNode}){return <section className="rounded-[28px] border border-black/[.07] bg-white p-5"><div className="flex items-center gap-3"><Icon className="size-4"/><h2 className="font-semibold">{title}</h2></div><div className="mt-5 space-y-2">{children}</div></section>}
function Row({label,value}:{label:string;value:number}){return <div className="flex items-center justify-between gap-3 rounded-2xl bg-black/[.035] px-4 py-3 text-sm"><span className="truncate capitalize">{label}</span><b>{value}</b></div>}
function Stat({icon:Icon,value,label}:{icon:React.ComponentType<{className?:string}>;value:number|string;label:string}){return <div><Icon className="size-4 text-violet-300"/><p className="mt-4 text-4xl font-semibold">{value}</p><p className="mt-1 text-xs text-white/40">{label}</p></div>}
