import { NextResponse } from "next/server";
import { z } from "zod";
import { requireApiSellerPermission } from "@/server/auth/principal";
import { getDatabase } from "@/server/db/client";
import { createSellerWebhookEndpoint, getSellerContext, testSellerWebhookEndpoint } from "@/server/seller/ops";
const createSchema=z.object({url:z.string().url(),events:z.array(z.enum(["catalog.updated","inventory.updated","evidence.updated","order.created","order.updated"])).min(1)});
const testSchema=z.object({endpointId:z.string().min(1)});
export async function GET(){const auth=await requireApiSellerPermission("seller:webhooks:manage");if(auth.response)return auth.response;const context=await getSellerContext(auth.principal.email);if(!context)return NextResponse.json({error:"Seller workspace not found"},{status:404});const db=await getDatabase();const [endpoints,deliveries]=await Promise.all([db.query(`SELECT id,url,status,events,secret_prefix,last_delivery_at,failure_count,created_at FROM seller_webhook_endpoints WHERE seller_id=$1 ORDER BY created_at DESC`,[context.sellerId]),db.query(`SELECT d.* FROM seller_webhook_deliveries d JOIN seller_webhook_endpoints e ON e.id=d.endpoint_id WHERE e.seller_id=$1 ORDER BY d.created_at DESC LIMIT 25`,[context.sellerId])]);return NextResponse.json({endpoints:endpoints.rows,deliveries:deliveries.rows});}
export async function POST(request:Request){const auth=await requireApiSellerPermission("seller:webhooks:manage");if(auth.response)return auth.response;const context=await getSellerContext(auth.principal.email);if(!context)return NextResponse.json({error:"Seller workspace not found"},{status:404});const body=await request.json();if(body.action==="test"){const parsed=testSchema.safeParse(body);if(!parsed.success)return NextResponse.json({error:"Invalid test request"},{status:400});return NextResponse.json(await testSellerWebhookEndpoint({sellerId:context.sellerId,endpointId:parsed.data.endpointId}));}const parsed=createSchema.safeParse(body);if(!parsed.success)return NextResponse.json({error:"Invalid webhook endpoint",details:parsed.error.flatten()},{status:400});return NextResponse.json(await createSellerWebhookEndpoint({sellerId:context.sellerId,...parsed.data}),{status:201});}
