import type { Metadata } from "next";
import { ArrowRight, Clock3, GitCommitHorizontal, History } from "lucide-react";
import Link from "next/link";
import { getPublications } from "@/server/public-repository";

export const metadata: Metadata = { title: "Market updates", description: "A public ledger of reviewed changes to VialGrade records." };
export const dynamic = "force-dynamic";
const labels:Record<string,string>={price:"Price",availability:"Availability",shipping_claim:"Shipping",shipping:"Shipping",batch_code:"Batch",batchCode:"Batch",report_date:"Report date",reportDate:"Report date",report_confirmed:"Report confirmation",reportConfirmed:"Report confirmation",report_issuer:"Report issuer",reportIssuer:"Report issuer"};
export default async function UpdatesPage(){const publications=await getPublications(); return <div className="mx-auto max-w-[1100px] px-5 py-16 sm:px-8 sm:py-24"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-[11px] font-bold uppercase tracking-[.2em] text-[#6d5dfc]">Public change ledger</p><h1 className="mt-4 text-5xl font-extrabold tracking-[-.065em] sm:text-7xl">Reviewed changes, in public.</h1><p className="mt-6 max-w-2xl text-base font-medium leading-7 text-[var(--muted)]">Every entry here was checked by a person before it went live, and keeps both the old and the new value. Nothing our software scrapes appears here until someone has reviewed it.</p></div><div className="ink-1 hard rounded-[18px] bg-white p-5"><History className="size-4 text-[#6d5dfc]"/><p className="mt-4 text-3xl font-extrabold">{publications.length}</p><p className="mt-1 text-xs text-[var(--muted)]">Visible receipts</p></div></div><div className="mt-12 space-y-4">{publications.map(item=><article key={item.id} className="ink-1 hard rounded-[18px] bg-white p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div className="flex flex-wrap items-center gap-2"><span className="ink-1 rounded-full bg-[#f7f7f4] px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.1em]">Version {item.version}</span><span className="inline-flex items-center gap-1 text-xs text-[var(--muted)]"><Clock3 className="size-3"/>{new Date(item.publishedAt).toLocaleString("en-US",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit"})}</span></div><h2 className="mt-4 text-xl font-extrabold tracking-[-.03em]">{item.productName}</h2><p className="mt-1 text-xs text-[var(--muted)]">{item.vendorName}</p></div><Link href={`/products/${item.listingSlug}`} className="inline-flex items-center gap-2 text-sm font-bold">Open record <ArrowRight className="size-4"/></Link></div><div className="mt-5 flex flex-wrap gap-2">{item.changedFields.map(field=><span key={field} className="ink-1 rounded-full bg-[#f0edff] px-3 py-1.5 text-[11px] font-bold text-[#6d5dfc]">{labels[field]??field.replaceAll("_"," ")}</span>)}</div><div className="mt-5 grid gap-3 sm:grid-cols-2"><State label="Before" value={summarize(item.before,item.changedFields)}/><State label="After" value={summarize(item.after,item.changedFields)} highlight/></div><p className="mt-4 flex items-center gap-2 text-[10px] text-[var(--muted)]"><GitCommitHorizontal className="size-3"/>Published by {item.publishedBy}</p></article>)}{publications.length===0&&<div className="rounded-[20px] border-2 border-dashed border-[#111214]/30 bg-white p-12 text-center"><History className="mx-auto size-6 text-[var(--muted)]"/><h2 className="mt-4 text-xl font-extrabold">No public changes yet.</h2><p className="mt-2 text-sm font-medium text-[var(--muted)]">Every change we publish will appear here, with the before and after.</p></div>}</div></div>}
function summarize(data:Record<string,unknown>,keys:string[]){return keys.slice(0,4).map(key=>`${labels[key]??key}: ${format(data[key])}`).join(" · ")||"No changed fields"}
function format(value:unknown){if(value===null||value===undefined||value==="")return "Not recorded"; if(typeof value==="boolean")return value?"Yes":"No"; return String(value)}
function State({label,value,highlight=false}:{label:string;value:string;highlight?:boolean}){return <div className={`ink-1 rounded-[14px] p-4 ${highlight?"bg-[#f0edff]":"bg-[#f7f7f4]"}`}><p className={`text-[10px] font-bold uppercase tracking-[.12em] ${highlight?"text-[#6d5dfc]":"text-[var(--muted)]"}`}>{label}</p><p className="mt-2 text-xs font-medium leading-5">{value}</p></div>}
