import type { Metadata } from "next";
import { ArrowRight, CheckCircle2, History } from "lucide-react";
import Link from "next/link";
import { requireStaff } from "@/server/auth/session";
import { getPublicationRecords } from "@/server/review/repository";

export const metadata: Metadata = { title: "Publication ledger" };
export const dynamic = "force-dynamic";
function changedKeys(before:Record<string,unknown>,after:Record<string,unknown>){return Object.keys(after).filter(key=>JSON.stringify(before[key])!==JSON.stringify(after[key]));}
function value(v:unknown){if(Array.isArray(v))return `${v.length} observations`;if(typeof v==="boolean")return v?"Yes":"No";if(v===null||v===undefined||v==="")return "Not recorded";return String(v)}

export default async function PublicationsPage({ searchParams }: { searchParams: Promise<{ published?: string }> }) {
  await requireStaff();
  const [records, params] = await Promise.all([getPublicationRecords(), searchParams]);
  return <div><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-[var(--muted)]">Append-only evidence history</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.055em] sm:text-5xl">Publication ledger</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-[var(--muted)]">Each receipt records the exact catalog state before and after a human-approved claim. New evidence supersedes presentation state without deleting history.</p>{params.published&&<div className="mt-6 flex items-center gap-2 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-900"><CheckCircle2 className="size-4"/>The claim was published and its receipt is now permanent.</div>}<div className="mt-8 space-y-4">{records.map(record=>{const keys=changedKeys(record.before,record.after);return <article key={record.id} className="rounded-[28px] border border-black/[.07] bg-white p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><span className="rounded-full bg-black/[.05] px-2.5 py-1 text-[10px] font-semibold uppercase">Version {record.version}</span><span className="text-xs text-[var(--muted)]">{new Date(record.publishedAt).toLocaleString()}</span></div><h2 className="mt-3 text-xl font-semibold tracking-[-.025em]">{record.productName}</h2><p className="mt-1 text-xs text-[var(--muted)]">{record.vendorName} · published by {record.publishedBy}</p></div><Link href={`/products/${record.listingSlug}`} className="text-xs font-semibold">Open record →</Link></div><div className="mt-5 grid gap-3">{keys.map(key=><div key={key} className="grid gap-3 rounded-2xl bg-[var(--background)] p-4 sm:grid-cols-[130px_1fr_auto_1fr] sm:items-center"><p className="text-xs font-semibold capitalize">{key.replace(/([A-Z])/g," $1")}</p><p className="break-words text-xs text-[var(--muted)]">{value(record.before[key])}</p><ArrowRight className="hidden size-3 text-black/25 sm:block"/><p className="break-words text-xs font-semibold">{value(record.after[key])}</p></div>)}</div><div className="mt-4 flex flex-wrap items-center gap-3 font-mono text-[10px] text-[var(--muted)]"><span>{record.id} · {record.publishedClaimIds.join(", ")}</span>{record.rootEventId&&<Link href={`/admin/traces#${record.rootEventId}`} className="font-sans font-semibold text-black">Open cascade →</Link>}</div></article>})}{records.length===0&&<div className="rounded-[28px] border border-dashed border-black/15 bg-white p-10 text-center"><History className="mx-auto size-6 text-black/30"/><h2 className="mt-4 text-xl font-semibold">No publications yet.</h2><p className="mt-2 text-sm text-[var(--muted)]">Approved claims will appear here with before and after state.</p></div>}</div></div>;
}
