import type { Metadata } from "next";
import { AgentRunTable } from "@/components/agent-run-table";
import { getRecentAgentRuns } from "@/server/catalog/repository";
import { getAdminMetrics } from "@/server/review/repository";
import { getRefreshMetrics } from "@/server/refresh/repository";
import { getIntelligenceMetrics, getPublicSignals, getTraceRoots } from "@/server/intelligence/repository";
import { Bell, Bot, Braces, Database, GitBranch, Lightbulb, RadioTower, ShieldCheck } from "lucide-react";
import Link from "next/link";

export const metadata: Metadata = { title: "Agent operations", description: "The live control architecture behind VIAL's source-backed catalog." };
export const dynamic = "force-dynamic";

export default async function OperationsPage() {
  const [runs, metrics, refresh, intelligence, traces, signals] = await Promise.all([getRecentAgentRuns(15), getAdminMetrics(), getRefreshMetrics(), getIntelligenceMetrics(), getTraceRoots(4), getPublicSignals(3)]);
  return <section className="mx-auto max-w-[1320px] px-5 py-14 sm:px-8 sm:py-20">
    <div className="mb-10 grid gap-8 lg:grid-cols-[1fr_.7fr] lg:items-end"><div><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-[var(--muted)]">Provenance control plane</p><h1 className="mt-3 text-5xl font-semibold leading-[.95] tracking-[-.065em] sm:text-6xl">Every consequence leaves a receipt.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-[var(--muted)]">A controlled source refresh creates an immutable snapshot and diff. Reviewed claims can then cascade into public records, metrics, alerts, vendor history, and market signals, all under one visible root event.</p></div><div className="rounded-[24px] border border-violet-200 bg-violet-50 p-5 text-sm leading-6 text-violet-900">The connected sources and companies remain fictional. The scheduler, persistence, retries, role gates, event lineage, alert generation, and publication receipts are functional. <Link href="/admin/login" className="font-semibold underline underline-offset-4">Open staff workspace</Link>.</div></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><OpsMetric icon={Bot} value={String(metrics.activeRuns)} label="Active workflows" detail="Running or awaiting human review"/><OpsMetric icon={RadioTower} value={String(refresh.enabled)} label="Controlled sources" detail={`${refresh.queued} jobs in the durable queue`}/><OpsMetric icon={GitBranch} value={String(intelligence.traces)} label="Causal traces" detail={`${intelligence.alerts} reviewed change alerts`}/><OpsMetric icon={Lightbulb} value={String(intelligence.open)} label="Open signals" detail="Second-order market conditions"/></div>
    <div className="mt-12 grid gap-5 lg:grid-cols-6"><PipelineStage icon={RadioTower} title="Scheduler" detail="Runs only enabled source policies with bounded retries."/><PipelineStage icon={ShieldCheck} title="Safe fetch" detail="Revalidates DNS, redirects, content type, timeout, and size."/><PipelineStage icon={Braces} title="Extraction" detail="Parses a schema-limited vocabulary from untrusted content."/><PipelineStage icon={Database} title="Review" detail="Keeps proposed changes separate from published state."/><PipelineStage icon={GitBranch} title="Cascade" detail="Carries one root through metrics, alerts, and history."/><PipelineStage icon={Lightbulb} title="Signals" detail="Surfaces market structure without making product recommendations."/></div>
    <div className="mt-14 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><section className="rounded-[28px] border border-black/[.07] bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-[var(--muted)]">Latest roots</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.04em]">Causal trace ledger</h2></div><GitBranch className="size-5 text-black/30"/></div><div className="mt-6 space-y-3">{traces.map(trace=><div key={trace.id} className="rounded-2xl bg-[var(--background)] p-4"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold">{trace.eventType}</p><p className="mt-1 font-mono text-[10px] text-black/55">{trace.id.slice(0,26)}</p></div><span className="rounded-full bg-white px-2.5 py-1 text-[10px] font-semibold">{trace.events.length} events</span></div><div className="mt-4 flex gap-4 text-[10px] text-[var(--muted)]"><span className="inline-flex items-center gap-1"><Bell className="size-3"/>{trace.alertCount} alerts</span><span className="inline-flex items-center gap-1"><Lightbulb className="size-3"/>{trace.opportunityCount} signals</span></div></div>)}{traces.length===0&&<p className="py-8 text-center text-sm text-[var(--muted)]">No causal traces yet.</p>}</div></section><section className="rounded-[28px] bg-[#111214] p-6 text-white"><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-white/60">Compounding intelligence</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.04em]">One change, multiple signals.</h2><div className="mt-6 space-y-3">{signals.map(signal=><Link href="/signals" key={signal.id} className="block rounded-2xl border border-white/[.08] bg-white/[.05] p-4 hover:bg-white/[.08]"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.13em] text-violet-300">{signal.signalType.replaceAll("-"," ")}</p><p className="mt-2 text-sm font-semibold">{signal.title}</p></div><span className="text-xl font-semibold tabular-nums">{Math.round(signal.score)}</span></div><p className="mt-2 text-xs leading-5 text-white/60">{signal.summary}</p></Link>)}{signals.length===0&&<p className="py-8 text-center text-sm text-white/60">Run the intelligence sweep to populate signals.</p>}</div><Link href="/signals" className="mt-5 inline-flex text-xs font-semibold text-white">Open market signals →</Link></section></div>
    <div className="mt-14"><div className="mb-6 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-[var(--muted)]">Run ledger</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.045em]">Recent tool loops</h2></div><p className="text-sm text-[var(--muted)]">Live local workflow records</p></div><AgentRunTable runs={runs}/></div>
  </section>;
}
function OpsMetric({icon:Icon,value,label,detail}:{icon:React.ComponentType<{className?:string}>;value:string;label:string;detail:string}){return <div className="rounded-[24px] border border-black/[.07] bg-white p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-3xl font-semibold tracking-[-0.05em]">{value}</p><p className="mt-1 text-sm font-semibold">{label}</p></div><span className="grid size-10 place-items-center rounded-xl bg-black/[.045]"><Icon className="size-4"/></span></div><p className="mt-5 text-xs leading-5 text-[var(--muted)]">{detail}</p></div>}
function PipelineStage({icon:Icon,title,detail}:{icon:React.ComponentType<{className?:string}>;title:string;detail:string}){return <div className="relative rounded-[24px] bg-[#111214] p-5 text-white"><span className="grid size-10 place-items-center rounded-xl bg-white/10"><Icon className="size-4"/></span><h2 className="mt-6 font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-white/50">{detail}</p></div>}
