import type { Metadata } from "next";
import { BookOpen, CircleHelp, Search, ShieldQuestion } from "lucide-react";
import Link from "next/link";
export const metadata:Metadata={title:"Help center",description:"Learn how to search, compare, interpret evidence, and use VialGrade responsibly."};
const faqs=[
["Does VialGrade sell products?","No. VialGrade is where you research the purchase — when you're ready to buy, we link you to the vendor's own site. VialGrade never handles payment or product. (Outbound vendor links switch on once the affiliate step is approved.)"],
["What does issuer confirmed mean?","The lab named on a report confirmed it really issued it — the paper is genuine. It doesn't prove the vial you'd receive matches the tested sample."],
["Why is there no safety score?","Because identity, dose, sterility, and batch matching are different questions. One blended score would hide whichever answer is missing — so we show each answer separately, including unknown."],
["Are the vendors and labs real?","Yes. Records come from real public sources — vendor product pages and the Janoshik lab-report feed — and are marked Live. A listing is never an endorsement either way."],
["Can VialGrade recommend a compound?","No. VialGrade organizes market and evidence information. It does not provide medical advice, dosing guidance, treatment selection, or product-use recommendations."],
["How do updates reach the public record?","Software captures a timestamped snapshot of the source and extracts the claims. A human reviewer approves each specific change before it appears publicly."],
];
export default function HelpPage(){return <div className="mx-auto max-w-[1100px] px-5 py-16 sm:px-8 sm:py-24"><div className="text-center"><p className="text-[11px] font-bold uppercase tracking-[.2em] text-[#6d5dfc]">Help center</p><h1 className="mt-4 text-5xl font-extrabold tracking-[-.065em] sm:text-7xl">How VialGrade works.</h1><p className="mx-auto mt-6 max-w-2xl text-base font-medium leading-7 text-[var(--muted)]">What the labels mean, how we check listings, and where VialGrade deliberately stops.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-3"><Quick icon={Search} href="/market" title="Search the market" text="Find a peptide, a vendor, or a specific batch."/><Quick icon={BookOpen} href="/research" title="Read the lab evidence" text="What a report proves, and what stays unknown."/><Quick icon={ShieldQuestion} href="/how-we-check" title="How we check" text="The evidence ladder, our limits, and who approves what."/></div><div className="mt-14"><div className="flex items-center gap-3"><CircleHelp className="size-5 text-[#6d5dfc]"/><h2 className="text-2xl font-extrabold tracking-[-.04em]">Frequently asked questions</h2></div><div className="ink-1 hard mt-6 divide-y divide-black/[.08] rounded-[18px] bg-white px-5 sm:px-7">{faqs.map(([q,a])=><details key={q} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 text-sm font-bold"><span>{q}</span><span className="text-xl font-light text-[var(--muted)] group-open:rotate-45">+</span></summary><p className="mt-3 max-w-3xl text-sm font-medium leading-6 text-[var(--muted)]">{a}</p></details>)}</div></div></div>}
function Quick({icon:Icon,href,title,text}:{icon:React.ComponentType<{className?:string}>;href:string;title:string;text:string}){return <Link href={href} className="ink-1 hard press rounded-[18px] bg-white p-5"><Icon className="size-4 text-[#6d5dfc]"/><h2 className="mt-6 text-sm font-bold">{title}</h2><p className="mt-2 text-xs font-medium leading-5 text-[var(--muted)]">{text}</p></Link>}
