import type { Metadata } from "next";
import { BookOpen, CircleHelp, Search, ShieldQuestion } from "lucide-react";
import Link from "next/link";
export const metadata:Metadata={title:"Help center",description:"Learn how to search, compare, interpret evidence, and use VIAL responsibly."};
const faqs=[
["Does VIAL sell products?","No. This prototype is information-only. It has no seller links, checkout, order routing, payment processing, or product fulfillment."],
["What does issuer confirmed mean?","It means the report identifier was represented as confirmed by the named issuing source. It does not establish that the physical inventory a user might encounter matches the tested sample."],
["Why is there no safety score?","Safety, identity, quantity, sterility, sampling, and batch linkage are different questions. Combining them into one score would imply certainty the evidence does not support."],
["Are the vendors and labs real?","No. Every vendor, listing, issuer, price, batch, rating, and review in this build is fictional demonstration data."],
["Can VIAL recommend a compound?","No. VIAL organizes market and evidence information. It does not provide medical advice, dosing guidance, treatment selection, or product-use recommendations."],
["How do updates reach the public record?","A controlled source creates an immutable snapshot, structured claims are extracted, and a human reviewer must approve a specific atomic change before it appears publicly."],
];
export default function HelpPage(){return <div className="mx-auto max-w-[1100px] px-5 py-16 sm:px-8 sm:py-24"><div className="text-center"><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-[var(--muted)]">Help center</p><h1 className="mt-4 text-5xl font-semibold tracking-[-.065em] sm:text-7xl">Understand the interface.</h1><p className="mx-auto mt-6 max-w-2xl text-base leading-7 text-[var(--muted)]">Learn how VIAL organizes records, what evidence labels mean, and where the product intentionally stops.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-3"><Quick icon={Search} href="/market" title="Search the market" text="Find normalized compounds, vendors, and listings."/><Quick icon={BookOpen} href="/research" title="Read evidence" text="Understand reports, batch linkage, and unknowns."/><Quick icon={ShieldQuestion} href="/methodology" title="Review standards" text="See publication gates, limitations, and governance."/></div><div className="mt-14"><div className="flex items-center gap-3"><CircleHelp className="size-5"/><h2 className="text-2xl font-semibold tracking-[-.04em]">Frequently asked questions</h2></div><div className="mt-6 divide-y divide-black/[.07] rounded-[28px] border border-black/[.07] bg-white px-5 sm:px-7">{faqs.map(([q,a])=><details key={q} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 text-sm font-semibold"><span>{q}</span><span className="text-xl font-light text-black/30 group-open:rotate-45">+</span></summary><p className="mt-3 max-w-3xl text-sm leading-6 text-[var(--muted)]">{a}</p></details>)}</div></div></div>}
function Quick({icon:Icon,href,title,text}:{icon:React.ComponentType<{className?:string}>;href:string;title:string;text:string}){return <Link href={href} className="rounded-[24px] border border-black/[.07] bg-white p-5 transition hover:-translate-y-0.5"><Icon className="size-4 text-violet-700"/><h2 className="mt-6 text-sm font-semibold">{title}</h2><p className="mt-2 text-xs leading-5 text-[var(--muted)]">{text}</p></Link>}
